ERROR 2018-10-25 10:34:52,443 exception 135 Internal Server Error: /image_codes/825236a0-7b77-4c58-8057-0ebcf0eff109/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/python/PycharmProjects/meiduo_sz/meiduo/meiduo/apps/verifications/views.py", line 82, in get
    redis_conn = get_redis_connection('verify_codes')
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django_redis/__init__.py", line 14, in get_redis_connection
    cache = caches[alias]
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/cache/__init__.py", line 77, in __getitem__
    "Could not find config for '%s' in settings.CACHES" % alias
django.core.cache.backends.base.InvalidCacheBackendError: Could not find config for 'verify_codes' in settings.CACHES
ERROR 2018-10-25 10:34:53,447 basehttp 124 "GET /image_codes/825236a0-7b77-4c58-8057-0ebcf0eff109/ HTTP/1.1" 500 17688
INFO 2018-10-25 10:35:00,387 basehttp 124 "GET /mobiles/13534325321/count/ HTTP/1.1" 200 34
INFO 2018-10-25 10:35:00,507 basehttp 124 "GET /mobiles/13534325321/count/ HTTP/1.1" 200 34
INFO 2018-10-25 10:35:07,771 basehttp 124 "GET /mobiles/13534325322/count/ HTTP/1.1" 200 34
INFO 2018-10-25 10:35:08,794 basehttp 124 "GET /mobiles/13534325322/count/ HTTP/1.1" 200 34
INFO 2018-10-25 10:35:32,464 basehttp 124 "GET /mobiles/13534325322/count/ HTTP/1.1" 200 34
ERROR 2018-10-25 10:35:38,916 exception 135 Internal Server Error: /image_codes/dda7ad91-a75c-4625-b4bf-34ca114b00e0/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/python/PycharmProjects/meiduo_sz/meiduo/meiduo/apps/verifications/views.py", line 82, in get
    redis_conn = get_redis_connection('verify_codes')
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django_redis/__init__.py", line 14, in get_redis_connection
    cache = caches[alias]
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/cache/__init__.py", line 77, in __getitem__
    "Could not find config for '%s' in settings.CACHES" % alias
django.core.cache.backends.base.InvalidCacheBackendError: Could not find config for 'verify_codes' in settings.CACHES
ERROR 2018-10-25 10:35:38,960 basehttp 124 "GET /image_codes/dda7ad91-a75c-4625-b4bf-34ca114b00e0/ HTTP/1.1" 500 17688
WARNING 2018-10-25 10:35:49,070 base 152 Not Found: /sms_codes/13534325322/
WARNING 2018-10-25 10:35:49,072 basehttp 124 "GET /sms_codes/13534325322/?text=17688&image_code_id=dda7ad91-a75c-4625-b4bf-34ca114b00e0 HTTP/1.1" 404 2995
INFO 2018-10-25 10:35:49,213 basehttp 124 "GET /mobiles/13534325322/count/ HTTP/1.1" 200 34
WARNING 2018-10-25 10:36:27,599 base 152 Not Found: /sms_codes/13534325322/
WARNING 2018-10-25 10:36:27,605 basehttp 124 "GET /sms_codes/13534325322/?text=17688&image_code_id=dda7ad91-a75c-4625-b4bf-34ca114b00e0 HTTP/1.1" 404 2995
INFO 2018-10-25 10:36:27,711 basehttp 124 "GET /mobiles/13534325322/count/ HTTP/1.1" 200 34
WARNING 2018-10-25 10:36:41,915 base 152 Not Found: /sms_codes/13534325322/
WARNING 2018-10-25 10:36:41,922 basehttp 124 "GET /sms_codes/13534325322/?text=2995&image_code_id=dda7ad91-a75c-4625-b4bf-34ca114b00e0 HTTP/1.1" 404 2994
INFO 2018-10-25 10:36:42,048 basehttp 124 "GET /mobiles/13534325322/count/ HTTP/1.1" 200 34
ERROR 2018-10-25 10:37:20,201 exception 135 Internal Server Error: /image_codes/7f1a79b4-d1fc-40aa-a674-a41d951d28bd/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/python/PycharmProjects/meiduo_sz/meiduo/meiduo/apps/verifications/views.py", line 82, in get
    redis_conn = get_redis_connection('verify_codes')
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django_redis/__init__.py", line 14, in get_redis_connection
    cache = caches[alias]
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/cache/__init__.py", line 77, in __getitem__
    "Could not find config for '%s' in settings.CACHES" % alias
django.core.cache.backends.base.InvalidCacheBackendError: Could not find config for 'verify_codes' in settings.CACHES
ERROR 2018-10-25 10:37:20,390 basehttp 124 "GET /image_codes/7f1a79b4-d1fc-40aa-a674-a41d951d28bd/ HTTP/1.1" 500 17688
INFO 2018-10-25 14:00:23,046 basehttp 124 "GET /image_codes/a59fadc1-eaa3-4dc3-a51d-6d2cbd87810c/ HTTP/1.1" 200 3396
INFO 2018-10-25 14:00:34,427 basehttp 124 "GET /mobiles/13534325321/count/ HTTP/1.1" 200 34
INFO 2018-10-25 14:00:39,225 basehttp 124 "GET /mobiles/13534325322/count/ HTTP/1.1" 200 34
INFO 2018-10-25 14:00:39,897 basehttp 124 "GET /image_codes/ec1f37a4-a8c0-4840-80a2-ae4a0462de17/ HTTP/1.1" 200 3419
INFO 2018-10-25 14:00:40,714 basehttp 124 "GET /image_codes/fd90a0e7-8886-4522-ae84-cd945bc7ff18/ HTTP/1.1" 200 2913
INFO 2018-10-25 14:00:41,614 basehttp 124 "GET /image_codes/e5293f73-70e9-47b0-a626-e5e3ce9d3fa8/ HTTP/1.1" 200 3580
INFO 2018-10-25 14:00:42,996 basehttp 124 "GET /image_codes/af988b10-6804-4c48-b71a-cc0012dd151b/ HTTP/1.1" 200 3444
INFO 2018-10-25 14:00:43,539 basehttp 124 "GET /image_codes/812c010a-706b-4e5a-aa7b-54130a161513/ HTTP/1.1" 200 3386
INFO 2018-10-25 14:01:16,541 basehttp 124 "GET /image_codes/70ee6c19-bd1c-434e-9ee1-f8a5341591f7/ HTTP/1.1" 200 3487
INFO 2018-10-25 14:01:20,506 basehttp 124 "GET /image_codes/f18272bc-3740-47a1-adbe-6efcc8a97f1f/ HTTP/1.1" 200 3352
INFO 2018-10-25 14:01:37,706 basehttp 124 "GET /image_codes/21b08a1b-b85d-429b-bb1a-443814ac0de1/ HTTP/1.1" 200 3092
WARNING 2018-10-25 14:01:43,767 base 152 Not Found: /sms_codes/13534325322/
WARNING 2018-10-25 14:01:43,838 basehttp 124 "GET /sms_codes/13534325322/?text=umyp&image_code_id=21b08a1b-b85d-429b-bb1a-443814ac0de1 HTTP/1.1" 404 2994
INFO 2018-10-25 14:01:44,032 basehttp 124 "GET /mobiles/13534325322/count/ HTTP/1.1" 200 34
WARNING 2018-10-25 14:01:58,792 base 152 Not Found: /sms_codes/13534325322/
WARNING 2018-10-25 14:01:58,793 basehttp 124 "GET /sms_codes/13534325322/?text=umyp&image_code_id=21b08a1b-b85d-429b-bb1a-443814ac0de1 HTTP/1.1" 404 2994
INFO 2018-10-25 14:01:58,839 basehttp 124 "GET /mobiles/13534325322/count/ HTTP/1.1" 200 34
WARNING 2018-10-25 14:02:00,453 base 152 Not Found: /sms_codes/13534325322/
WARNING 2018-10-25 14:02:00,454 basehttp 124 "GET /sms_codes/13534325322/?text=umyp&image_code_id=21b08a1b-b85d-429b-bb1a-443814ac0de1 HTTP/1.1" 404 2994
INFO 2018-10-25 14:02:00,511 basehttp 124 "GET /mobiles/13534325322/count/ HTTP/1.1" 200 34
INFO 2018-10-25 14:30:02,964 basehttp 124 "GET /image_codes/2bb1dfc7-adde-4c65-9224-b2e86b4ca045/ HTTP/1.1" 200 2911
INFO 2018-10-25 14:30:10,896 basehttp 124 "GET /mobiles/13534325321/count/ HTTP/1.1" 200 34
INFO 2018-10-25 14:30:14,414 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
WARNING 2018-10-25 14:30:17,313 base 152 Not Found: /sms_codes/13534325323/
WARNING 2018-10-25 14:30:17,314 basehttp 124 "GET /sms_codes/13534325323/?text=fyal&image_code_id=2bb1dfc7-adde-4c65-9224-b2e86b4ca045 HTTP/1.1" 404 2994
INFO 2018-10-25 14:30:17,354 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
WARNING 2018-10-25 14:36:47,713 base 152 Not Found: /sms_codes/13534325323/
WARNING 2018-10-25 14:36:47,719 basehttp 124 "GET /sms_codes/13534325323/?text=fyal&image_code_id=2bb1dfc7-adde-4c65-9224-b2e86b4ca045 HTTP/1.1" 404 2994
INFO 2018-10-25 14:36:47,753 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
INFO 2018-10-25 14:41:26,127 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
WARNING 2018-10-25 14:41:31,000 base 152 Not Found: /sms_codes/13534325323/
WARNING 2018-10-25 14:41:31,001 basehttp 124 "GET /sms_codes/13534325323/?text=fyal&image_code_id=2bb1dfc7-adde-4c65-9224-b2e86b4ca045 HTTP/1.1" 404 2994
INFO 2018-10-25 14:41:31,034 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
WARNING 2018-10-25 14:41:31,408 base 152 Not Found: /sms_codes/13534325323/
WARNING 2018-10-25 14:41:31,409 basehttp 124 "GET /sms_codes/13534325323/?text=fyal&image_code_id=2bb1dfc7-adde-4c65-9224-b2e86b4ca045 HTTP/1.1" 404 2994
INFO 2018-10-25 14:41:31,439 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
INFO 2018-10-25 14:48:47,990 basehttp 124 "GET /image_codes/b838e6b6-7b19-43fd-b9f0-419de94058db/ HTTP/1.1" 200 3086
WARNING 2018-10-25 14:49:03,465 base 152 Not Found: /sms_codes/13534325323/
WARNING 2018-10-25 14:49:03,482 basehttp 124 "GET /sms_codes/13534325323/?text=fyal&image_code_id=b838e6b6-7b19-43fd-b9f0-419de94058db HTTP/1.1" 404 2994
INFO 2018-10-25 14:49:03,684 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
WARNING 2018-10-25 14:49:06,704 base 152 Not Found: /sms_codes/13534325323/
WARNING 2018-10-25 14:49:06,709 basehttp 124 "GET /sms_codes/13534325323/?text=fyal&image_code_id=b838e6b6-7b19-43fd-b9f0-419de94058db HTTP/1.1" 404 2994
INFO 2018-10-25 14:49:06,811 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
WARNING 2018-10-25 14:49:20,138 base 152 Not Found: /sms_codes/13534325323/
WARNING 2018-10-25 14:49:20,141 basehttp 124 "GET /sms_codes/13534325323/?text=g8s4&image_code_id=b838e6b6-7b19-43fd-b9f0-419de94058db HTTP/1.1" 404 2994
INFO 2018-10-25 14:49:20,296 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
WARNING 2018-10-25 14:49:23,712 base 152 Not Found: /sms_codes/13534325323/
WARNING 2018-10-25 14:49:23,713 basehttp 124 "GET /sms_codes/13534325323/?text=g8s4&image_code_id=b838e6b6-7b19-43fd-b9f0-419de94058db HTTP/1.1" 404 2994
INFO 2018-10-25 14:49:23,745 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
WARNING 2018-10-25 14:49:24,880 base 152 Not Found: /sms_codes/13534325323/
WARNING 2018-10-25 14:49:24,880 basehttp 124 "GET /sms_codes/13534325323/?text=g8s4&image_code_id=b838e6b6-7b19-43fd-b9f0-419de94058db HTTP/1.1" 404 2994
INFO 2018-10-25 14:49:24,913 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
WARNING 2018-10-25 14:49:25,030 base 152 Not Found: /sms_codes/13534325323/
WARNING 2018-10-25 14:49:25,031 basehttp 124 "GET /sms_codes/13534325323/?text=g8s4&image_code_id=b838e6b6-7b19-43fd-b9f0-419de94058db HTTP/1.1" 404 2994
INFO 2018-10-25 14:49:25,068 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
WARNING 2018-10-25 14:49:25,331 base 152 Not Found: /sms_codes/13534325323/
WARNING 2018-10-25 14:49:25,332 basehttp 124 "GET /sms_codes/13534325323/?text=g8s4&image_code_id=b838e6b6-7b19-43fd-b9f0-419de94058db HTTP/1.1" 404 2994
INFO 2018-10-25 14:49:25,363 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
WARNING 2018-10-25 14:49:25,921 base 152 Not Found: /sms_codes/13534325323/
WARNING 2018-10-25 14:49:25,922 basehttp 124 "GET /sms_codes/13534325323/?text=g8s4&image_code_id=b838e6b6-7b19-43fd-b9f0-419de94058db HTTP/1.1" 404 2994
INFO 2018-10-25 14:49:25,952 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
WARNING 2018-10-25 14:49:26,092 base 152 Not Found: /sms_codes/13534325323/
WARNING 2018-10-25 14:49:26,092 basehttp 124 "GET /sms_codes/13534325323/?text=g8s4&image_code_id=b838e6b6-7b19-43fd-b9f0-419de94058db HTTP/1.1" 404 2994
INFO 2018-10-25 14:49:26,110 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
WARNING 2018-10-25 14:49:26,468 base 152 Not Found: /sms_codes/13534325323/
WARNING 2018-10-25 14:49:26,470 basehttp 124 "GET /sms_codes/13534325323/?text=g8s4&image_code_id=b838e6b6-7b19-43fd-b9f0-419de94058db HTTP/1.1" 404 2994
INFO 2018-10-25 14:49:26,505 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
WARNING 2018-10-25 14:49:26,631 base 152 Not Found: /sms_codes/13534325323/
WARNING 2018-10-25 14:49:26,633 basehttp 124 "GET /sms_codes/13534325323/?text=g8s4&image_code_id=b838e6b6-7b19-43fd-b9f0-419de94058db HTTP/1.1" 404 2994
INFO 2018-10-25 14:49:26,661 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
WARNING 2018-10-25 14:49:27,504 base 152 Not Found: /sms_codes/13534325323/
WARNING 2018-10-25 14:49:27,506 basehttp 124 "GET /sms_codes/13534325323/?text=g8s4&image_code_id=b838e6b6-7b19-43fd-b9f0-419de94058db HTTP/1.1" 404 2994
INFO 2018-10-25 14:49:27,531 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
WARNING 2018-10-25 14:59:12,410 base 152 Not Found: /sms_codes/13534325323/
WARNING 2018-10-25 14:59:12,415 basehttp 124 "GET /sms_codes/13534325323/?text=g8s4&image_code_id=b838e6b6-7b19-43fd-b9f0-419de94058db HTTP/1.1" 404 2994
INFO 2018-10-25 14:59:12,576 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
INFO 2018-10-25 15:03:07,414 basehttp 124 "GET /image_codes/1ed279fb-b6f3-4145-bdf2-f9dd5e75e9c3/ HTTP/1.1" 200 2911
INFO 2018-10-25 15:03:27,606 basehttp 124 "GET /image_codes/f9ae64e8-562f-4df2-88c8-d9177ad9fc2c/ HTTP/1.1" 200 2857
INFO 2018-10-25 15:04:17,138 basehttp 124 "GET /mobiles/13534325321/count/ HTTP/1.1" 200 34
INFO 2018-10-25 15:04:22,041 basehttp 124 "GET /mobiles/13534325321/count/ HTTP/1.1" 200 34
INFO 2018-10-25 15:04:58,714 basehttp 124 "GET /mobiles/13534325327/count/ HTTP/1.1" 200 34
INFO 2018-10-25 15:05:01,038 basehttp 124 "GET /mobiles/13534325327/count/ HTTP/1.1" 200 34
WARNING 2018-10-25 15:05:01,153 basehttp 124 "GET /sms_code/13534325327/ HTTP/1.1" 400 82
WARNING 2018-10-25 15:05:23,817 basehttp 124 "GET /sms_code/13534325327/ HTTP/1.1" 400 82
WARNING 2018-10-25 15:05:23,953 basehttp 124 "GET /sms_code/13534325327/ HTTP/1.1" 400 82
INFO 2018-10-25 15:05:24,147 basehttp 124 "GET /mobiles/13534325327/count/ HTTP/1.1" 200 34
INFO 2018-10-25 15:05:24,235 basehttp 124 "GET /mobiles/13534325327/count/ HTTP/1.1" 200 34
INFO 2018-10-25 15:05:24,260 basehttp 124 "GET /mobiles/13534325327/count/ HTTP/1.1" 200 34
WARNING 2018-10-25 15:05:47,728 basehttp 124 "GET /sms_code/13534325323/ HTTP/1.1" 400 82
INFO 2018-10-25 15:05:48,266 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
INFO 2018-10-25 15:05:48,299 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
INFO 2018-10-25 15:07:33,691 basehttp 124 "GET /image_codes/43c256e4-6eb4-4dad-9775-d66a4a80cb56/ HTTP/1.1" 200 3208
INFO 2018-10-25 15:07:38,714 basehttp 124 "GET /mobiles/13534325321/count/ HTTP/1.1" 200 34
INFO 2018-10-25 15:07:45,046 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
INFO 2018-10-25 15:07:46,724 basehttp 124 "GET /image_codes/14c49bca-1361-40a3-86c0-6f8e0f32e746/ HTTP/1.1" 200 3294
WARNING 2018-10-25 15:07:49,877 base 152 Not Found: /sms_codes/13534325323/
WARNING 2018-10-25 15:07:49,879 basehttp 124 "GET /sms_codes/13534325323/?text=ewfd&image_code_id=14c49bca-1361-40a3-86c0-6f8e0f32e746 HTTP/1.1" 404 2994
INFO 2018-10-25 15:07:49,917 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
INFO 2018-10-25 17:50:28,015 basehttp 124 "GET /image_codes/e4d58855-6966-4ddb-b6e7-e00842aa3d0c/ HTTP/1.1" 200 3276
INFO 2018-10-25 17:51:22,873 basehttp 124 "GET /mobiles/13534325322/count/ HTTP/1.1" 200 34
WARNING 2018-10-25 17:51:26,159 base 152 Not Found: /sms_codes/13534325322/
WARNING 2018-10-25 17:51:26,160 basehttp 124 "GET /sms_codes/13534325322/?text=kclr&image_code_id=e4d58855-6966-4ddb-b6e7-e00842aa3d0c HTTP/1.1" 404 2994
INFO 2018-10-25 17:51:26,175 basehttp 124 "GET /mobiles/13534325322/count/ HTTP/1.1" 200 34
WARNING 2018-10-25 17:51:52,512 base 152 Not Found: /sms_codes/13534325322/
WARNING 2018-10-25 17:51:52,519 basehttp 124 "GET /sms_codes/13534325322/?text=kclr&image_code_id=e4d58855-6966-4ddb-b6e7-e00842aa3d0c HTTP/1.1" 404 2994
INFO 2018-10-25 17:51:52,693 basehttp 124 "GET /mobiles/13534325322/count/ HTTP/1.1" 200 34
WARNING 2018-10-25 17:52:02,371 base 152 Not Found: /sms_codes/13534325322/
WARNING 2018-10-25 17:52:02,374 basehttp 124 "GET /sms_codes/13534325322/?text=dss&image_code_id=e4d58855-6966-4ddb-b6e7-e00842aa3d0c HTTP/1.1" 404 2993
INFO 2018-10-25 17:52:02,507 basehttp 124 "GET /mobiles/13534325322/count/ HTTP/1.1" 200 34
INFO 2018-10-25 17:52:13,296 basehttp 124 "GET /image_codes/9ee7d815-7321-48a7-8f46-0d826d3aa50e/ HTTP/1.1" 200 3030
WARNING 2018-10-25 17:52:14,293 base 152 Not Found: /sms_codes/13534325322/
WARNING 2018-10-25 17:52:14,294 basehttp 124 "GET /sms_codes/13534325322/?text=dss&image_code_id=9ee7d815-7321-48a7-8f46-0d826d3aa50e HTTP/1.1" 404 2993
INFO 2018-10-25 17:52:14,321 basehttp 124 "GET /mobiles/13534325322/count/ HTTP/1.1" 200 34
INFO 2018-10-25 17:55:14,621 basehttp 124 "GET /image_codes/eb5d530c-72ea-4ef2-aa2d-4ba10d162aa7/ HTTP/1.1" 200 3421
INFO 2018-10-25 17:55:35,002 basehttp 124 "GET /image_codes/18131a07-e1cf-4e07-9044-cd245e093268/ HTTP/1.1" 200 3114
INFO 2018-10-25 19:30:53,469 basehttp 124 "GET /image_codes/8fe1ba98-e3c7-41a4-b895-b24258eefbd5/ HTTP/1.1" 200 3186
INFO 2018-10-25 19:30:56,935 basehttp 124 "GET /mobiles/13534325322/count/ HTTP/1.1" 200 34
WARNING 2018-10-25 19:30:59,677 base 152 Not Found: /sms_codes/13534325322/
WARNING 2018-10-25 19:30:59,678 basehttp 124 "GET /sms_codes/13534325322/?text=wewa&image_code_id=8fe1ba98-e3c7-41a4-b895-b24258eefbd5 HTTP/1.1" 404 2994
INFO 2018-10-25 19:30:59,693 basehttp 124 "GET /mobiles/13534325322/count/ HTTP/1.1" 200 34
INFO 2018-10-25 19:32:29,202 basehttp 124 "GET /mobiles/13534325321/count/ HTTP/1.1" 200 34
INFO 2018-10-25 19:56:35,928 basehttp 124 "GET /image_codes/2738a389-7644-41e7-a0f5-fe655bd001b0/ HTTP/1.1" 200 3244
INFO 2018-10-25 19:56:40,155 basehttp 124 "GET /image_codes/66da72bc-5911-4937-982a-013c33e5424b/ HTTP/1.1" 200 3230
INFO 2018-10-25 19:56:40,228 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
WARNING 2018-10-25 19:56:42,053 basehttp 124 "GET /sms_codes/13534325323/?text=sdfa&image_code_id=66da72bc-5911-4937-982a-013c33e5424b HTTP/1.1" 400 52
INFO 2018-10-25 19:56:42,083 basehttp 124 "GET /image_codes/2fe8e5ef-da1f-4de8-af15-1028828bbfc7/ HTTP/1.1" 200 3205
INFO 2018-10-25 19:56:42,097 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
INFO 2018-10-25 19:56:48,681 basehttp 124 "GET /image_codes/1110169d-f3a6-4824-bdf2-01b400940aa0/ HTTP/1.1" 200 3162
WARNING 2018-10-25 19:56:49,948 basehttp 124 "GET /sms_codes/13534325323/?text=sdfa&image_code_id=1110169d-f3a6-4824-bdf2-01b400940aa0 HTTP/1.1" 400 52
INFO 2018-10-25 19:56:49,980 basehttp 124 "GET /image_codes/52d2e99e-6527-4766-9437-6b514e736b14/ HTTP/1.1" 200 3368
INFO 2018-10-25 19:56:50,032 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
WARNING 2018-10-25 19:56:50,576 basehttp 124 "GET /sms_codes/13534325323/?text=sdfa&image_code_id=52d2e99e-6527-4766-9437-6b514e736b14 HTTP/1.1" 400 52
INFO 2018-10-25 19:56:50,609 basehttp 124 "GET /image_codes/ff70cce9-2df6-4069-a45e-1e2a75d1a6c1/ HTTP/1.1" 200 3201
INFO 2018-10-25 19:56:50,624 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
WARNING 2018-10-25 19:56:50,958 basehttp 124 "GET /sms_codes/13534325323/?text=sdfa&image_code_id=ff70cce9-2df6-4069-a45e-1e2a75d1a6c1 HTTP/1.1" 400 52
INFO 2018-10-25 19:56:50,995 basehttp 124 "GET /image_codes/86545b43-2c93-4664-9ad0-a9f5178cc2d2/ HTTP/1.1" 200 2868
INFO 2018-10-25 19:56:51,027 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
INFO 2018-10-25 19:56:56,012 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
ERROR 2018-10-25 19:56:56,018 exception 135 Internal Server Error: /sms_codes/13534325323/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/python/PycharmProjects/meiduo_sz/meiduo/meiduo/apps/verifications/views.py", line 71, in get
    send_sms_code.delay(mobile,sms_code)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/celery/app/task.py", line 408, in delay
    return self.apply_async(args, kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/celery/app/task.py", line 513, in apply_async
    check_arguments(*(args or ()), **(kwargs or {}))
TypeError: send_sms_code() missing 2 required positional arguments: 'expires' and 'template_id'
ERROR 2018-10-25 19:56:56,146 basehttp 124 "GET /sms_codes/13534325323/?text=hu7v&image_code_id=86545b43-2c93-4664-9ad0-a9f5178cc2d2 HTTP/1.1" 500 17867
WARNING 2018-10-25 19:57:04,588 basehttp 124 "GET /sms_codes/13534325323/?text=hu7v&image_code_id=86545b43-2c93-4664-9ad0-a9f5178cc2d2 HTTP/1.1" 400 40
INFO 2018-10-25 19:57:04,616 basehttp 124 "GET /image_codes/519068eb-d27f-48fa-b1e7-f213d3d35dc2/ HTTP/1.1" 200 3182
INFO 2018-10-25 19:57:04,634 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
WARNING 2018-10-25 19:57:19,201 basehttp 124 "GET /sms_codes/13534325323/?text=hu7v&image_code_id=519068eb-d27f-48fa-b1e7-f213d3d35dc2 HTTP/1.1" 400 52
INFO 2018-10-25 19:57:19,304 basehttp 124 "GET /image_codes/79fcb39b-8906-495f-b870-2afc72f4eaa4/ HTTP/1.1" 200 3084
INFO 2018-10-25 19:57:19,347 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
WARNING 2018-10-25 19:57:20,482 basehttp 124 "GET /sms_codes/13534325323/?text=hu7v&image_code_id=79fcb39b-8906-495f-b870-2afc72f4eaa4 HTTP/1.1" 400 52
INFO 2018-10-25 19:57:20,538 basehttp 124 "GET /image_codes/9d29639c-da57-4b3a-bc9a-0b593b12e0de/ HTTP/1.1" 200 3024
INFO 2018-10-25 19:57:20,576 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
WARNING 2018-10-25 19:57:43,740 basehttp 124 "GET /sms_codes/13534325323/?text=q45a&image_code_id=9d29639c-da57-4b3a-bc9a-0b593b12e0de HTTP/1.1" 400 43
INFO 2018-10-25 19:57:43,915 basehttp 124 "GET /image_codes/4dee44b6-6a88-4145-94fb-7d3f87fa14cf/ HTTP/1.1" 200 3256
INFO 2018-10-25 19:57:44,005 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
WARNING 2018-10-25 19:57:48,723 basehttp 124 "GET /sms_codes/13534325323/?text=kucc&image_code_id=4dee44b6-6a88-4145-94fb-7d3f87fa14cf HTTP/1.1" 400 43
INFO 2018-10-25 19:57:48,746 basehttp 124 "GET /image_codes/6ce1f8a6-1e25-4a87-abf8-4bc43024166e/ HTTP/1.1" 200 3183
INFO 2018-10-25 19:57:48,772 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
INFO 2018-10-25 19:57:51,136 basehttp 124 "GET /image_codes/7369c627-3f08-4bde-a187-86ed250d8c76/ HTTP/1.1" 200 3088
WARNING 2018-10-25 19:57:55,138 basehttp 124 "GET /sms_codes/13534325323/?text=dkpz&image_code_id=7369c627-3f08-4bde-a187-86ed250d8c76 HTTP/1.1" 400 43
INFO 2018-10-25 19:57:55,162 basehttp 124 "GET /image_codes/3367a31d-cb75-4e60-8a85-adf35453fd7e/ HTTP/1.1" 200 3239
INFO 2018-10-25 19:57:55,183 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
INFO 2018-10-25 19:58:09,008 basehttp 124 "GET /image_codes/043634de-3471-4ffd-9b5e-0a6377b70dcc/ HTTP/1.1" 200 3447
INFO 2018-10-25 19:58:33,816 basehttp 124 "GET /mobiles/13534325321/count/ HTTP/1.1" 200 34
INFO 2018-10-25 19:58:36,683 basehttp 124 "GET /mobiles/13534325322/count/ HTTP/1.1" 200 34
ERROR 2018-10-25 19:58:40,595 exception 135 Internal Server Error: /sms_codes/13534325322/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/python/PycharmProjects/meiduo_sz/meiduo/meiduo/apps/verifications/views.py", line 71, in get
    send_sms_code.delay(mobile,sms_code)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/celery/app/task.py", line 408, in delay
    return self.apply_async(args, kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/celery/app/task.py", line 513, in apply_async
    check_arguments(*(args or ()), **(kwargs or {}))
TypeError: send_sms_code() missing 2 required positional arguments: 'expires' and 'template_id'
INFO 2018-10-25 19:58:40,638 basehttp 124 "GET /mobiles/13534325322/count/ HTTP/1.1" 200 34
ERROR 2018-10-25 19:58:40,640 basehttp 124 "GET /sms_codes/13534325322/?text=tpam&image_code_id=043634de-3471-4ffd-9b5e-0a6377b70dcc HTTP/1.1" 500 17867
WARNING 2018-10-25 19:58:57,737 basehttp 124 "GET /sms_codes/13534325322/?text=tpam&image_code_id=043634de-3471-4ffd-9b5e-0a6377b70dcc HTTP/1.1" 400 40
INFO 2018-10-25 19:58:57,774 basehttp 124 "GET /mobiles/13534325322/count/ HTTP/1.1" 200 34
INFO 2018-10-25 19:58:57,904 basehttp 124 "GET /image_codes/06b93ac9-c50b-41ae-a30c-07247fac28f0/ HTTP/1.1" 200 3311
INFO 2018-10-25 19:59:00,182 basehttp 124 "GET /image_codes/f9cc80a5-7fd7-41c2-b5c6-0e161e5d3eb5/ HTTP/1.1" 200 2801
INFO 2018-10-25 19:59:00,763 basehttp 124 "GET /image_codes/0ed164b4-a1f3-4bf9-83cd-700929a17804/ HTTP/1.1" 200 3731
INFO 2018-10-25 19:59:01,166 basehttp 124 "GET /image_codes/24c83162-c2dc-4014-bf73-9a62f6c38aa6/ HTTP/1.1" 200 3315
INFO 2018-10-25 19:59:01,719 basehttp 124 "GET /image_codes/dac43fdf-a3c6-4508-bbb6-7d3287c340ff/ HTTP/1.1" 200 4112
WARNING 2018-10-25 19:59:06,261 basehttp 124 "GET /sms_codes/13534325322/?text=naew&image_code_id=dac43fdf-a3c6-4508-bbb6-7d3287c340ff HTTP/1.1" 400 43
INFO 2018-10-25 19:59:06,310 basehttp 124 "GET /image_codes/2dd73e8b-2fcb-47f9-b89e-4efa4f0b7104/ HTTP/1.1" 200 2868
INFO 2018-10-25 19:59:06,373 basehttp 124 "GET /mobiles/13534325322/count/ HTTP/1.1" 200 34
WARNING 2018-10-25 19:59:07,663 basehttp 124 "GET /sms_codes/13534325322/?text=naew&image_code_id=2dd73e8b-2fcb-47f9-b89e-4efa4f0b7104 HTTP/1.1" 400 52
INFO 2018-10-25 19:59:07,731 basehttp 124 "GET /image_codes/308c2e87-8ae6-4e6d-b68e-528d8c4aea31/ HTTP/1.1" 200 3230
INFO 2018-10-25 19:59:07,747 basehttp 124 "GET /mobiles/13534325322/count/ HTTP/1.1" 200 34
INFO 2018-10-25 19:59:11,610 basehttp 124 "GET /mobiles/13534325322/count/ HTTP/1.1" 200 34
WARNING 2018-10-25 19:59:13,022 basehttp 124 "GET /sms_codes/13534325322/?text=wyvd&image_code_id=308c2e87-8ae6-4e6d-b68e-528d8c4aea31 HTTP/1.1" 400 43
INFO 2018-10-25 19:59:13,049 basehttp 124 "GET /image_codes/9679efed-2a6d-4802-adb8-8f0600c640bb/ HTTP/1.1" 200 2909
INFO 2018-10-25 19:59:13,064 basehttp 124 "GET /mobiles/13534325322/count/ HTTP/1.1" 200 34
INFO 2018-10-25 20:21:43,350 basehttp 124 "GET /image_codes/dfb00469-3da5-4d16-a7a8-3c1daea80e2b/ HTTP/1.1" 200 3368
INFO 2018-10-25 20:21:46,651 basehttp 124 "GET /mobiles/13534325322/count/ HTTP/1.1" 200 34
WARNING 2018-10-25 20:21:50,322 basehttp 124 "GET /sms_codes/13534325322/?text=ws&image_code_id=dfb00469-3da5-4d16-a7a8-3c1daea80e2b HTTP/1.1" 400 61
INFO 2018-10-25 20:21:50,354 basehttp 124 "GET /image_codes/85924d3e-4840-4d20-9842-3aefbb0d6ef1/ HTTP/1.1" 200 2927
INFO 2018-10-25 20:21:50,382 basehttp 124 "GET /mobiles/13534325322/count/ HTTP/1.1" 200 34
WARNING 2018-10-25 20:21:55,036 basehttp 124 "GET /sms_codes/13534325322/?text=s2t8&image_code_id=85924d3e-4840-4d20-9842-3aefbb0d6ef1 HTTP/1.1" 400 52
INFO 2018-10-25 20:21:55,059 basehttp 124 "GET /image_codes/26c94d63-aba4-42a7-aeba-cbeb216a64c4/ HTTP/1.1" 200 3159
INFO 2018-10-25 20:21:55,101 basehttp 124 "GET /mobiles/13534325322/count/ HTTP/1.1" 200 34
INFO 2018-10-25 20:21:56,781 basehttp 124 "GET /image_codes/280e8112-4f97-40b8-a693-acd180a1c72f/ HTTP/1.1" 200 3592
INFO 2018-10-25 20:21:59,670 basehttp 124 "GET /mobiles/13534325322/count/ HTTP/1.1" 200 34
INFO 2018-10-25 20:22:01,447 basehttp 124 "GET /mobiles/13534325322/count/ HTTP/1.1" 200 34
ERROR 2018-10-25 20:22:01,452 exception 135 Internal Server Error: /sms_codes/13534325322/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/python/PycharmProjects/meiduo_sz/meiduo/meiduo/apps/verifications/views.py", line 62, in get
    send_sms_code.delay(mobile,sms_code)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/celery/app/task.py", line 408, in delay
    return self.apply_async(args, kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/celery/app/task.py", line 513, in apply_async
    check_arguments(*(args or ()), **(kwargs or {}))
TypeError: send_sms_code() missing 2 required positional arguments: 'expires' and 'template_id'
ERROR 2018-10-25 20:22:01,589 basehttp 124 "GET /sms_codes/13534325322/?text=uvxw&image_code_id=280e8112-4f97-40b8-a693-acd180a1c72f HTTP/1.1" 500 17904
INFO 2018-10-25 20:33:54,130 basehttp 124 "GET /image_codes/f1f67736-8248-414b-87ed-ac62fcef1d7d/ HTTP/1.1" 200 3457
INFO 2018-10-25 20:33:57,119 basehttp 124 "GET /image_codes/e215d946-ed01-4eb9-8d14-158f308bab56/ HTTP/1.1" 200 3197
INFO 2018-10-25 20:33:57,130 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
INFO 2018-10-25 20:33:58,355 basehttp 124 "GET /image_codes/0a592112-6808-4bbd-9411-da82c0a3a2cf/ HTTP/1.1" 200 2879
INFO 2018-10-25 20:34:01,048 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
INFO 2018-10-25 20:34:01,161 basehttp 124 "GET /sms_codes/13534325323/?text=asfw&image_code_id=0a592112-6808-4bbd-9411-da82c0a3a2cf HTTP/1.1" 200 16
WARNING 2018-10-25 20:35:30,350 basehttp 124 "GET /sms_codes/13534325323/?text=asfw&image_code_id=0a592112-6808-4bbd-9411-da82c0a3a2cf HTTP/1.1" 400 40
INFO 2018-10-25 20:35:30,545 basehttp 124 "GET /image_codes/5e6fedd2-98ef-4719-bb3b-7653c57e7df5/ HTTP/1.1" 200 3828
INFO 2018-10-25 20:35:30,600 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
INFO 2018-10-25 20:35:33,667 basehttp 124 "GET /sms_codes/13534325323/?text=bdzw&image_code_id=5e6fedd2-98ef-4719-bb3b-7653c57e7df5 HTTP/1.1" 200 16
INFO 2018-10-25 20:35:33,686 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
INFO 2018-10-25 20:36:23,116 basehttp 124 "GET /image_codes/3d07926c-31fb-4731-8bff-b40ea34f90e8/ HTTP/1.1" 200 3296
INFO 2018-10-25 20:36:25,846 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
WARNING 2018-10-25 20:36:29,356 basehttp 124 "GET /sms_codes/13534325323/?text=nvlb&image_code_id=3d07926c-31fb-4731-8bff-b40ea34f90e8 HTTP/1.1" 400 52
INFO 2018-10-25 20:36:29,377 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
INFO 2018-10-25 20:36:29,386 basehttp 124 "GET /image_codes/2b425585-03b2-45c7-8229-a1809b4c37e8/ HTTP/1.1" 200 2783
INFO 2018-10-25 20:36:36,300 basehttp 124 "GET /image_codes/6bc8fe99-197d-40e1-9a47-b9518d4f3f8c/ HTTP/1.1" 200 3205
INFO 2018-10-25 20:36:42,501 basehttp 124 "GET /sms_codes/13534325323/?text=wtqp&image_code_id=6bc8fe99-197d-40e1-9a47-b9518d4f3f8c HTTP/1.1" 200 16
INFO 2018-10-25 20:36:42,524 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
ERROR 2018-10-25 20:41:06,112 exception 80 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2018-10-25 20:41:06,534 basehttp 124 "GET / HTTP/1.1" 400 70767
ERROR 2018-10-25 20:41:07,751 exception 80 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2018-10-25 20:41:07,846 basehttp 124 "GET /favicon.ico HTTP/1.1" 400 70820
INFO 2018-10-25 20:41:12,450 basehttp 124 "GET /image_codes/3ec0d4e3-1c2e-4072-a851-e61a52de0b72/ HTTP/1.1" 200 2899
INFO 2018-10-25 20:41:16,095 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
INFO 2018-10-25 20:41:18,135 basehttp 124 "GET /mobiles/13534325323/count/ HTTP/1.1" 200 34
INFO 2018-10-25 20:41:18,218 basehttp 124 "GET /sms_codes/13534325323/?text=dqgc&image_code_id=3ec0d4e3-1c2e-4072-a851-e61a52de0b72 HTTP/1.1" 200 16
INFO 2018-10-25 23:29:57,551 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
WARNING 2018-10-25 23:29:57,743 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
WARNING 2018-10-25 23:30:03,840 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
WARNING 2018-10-25 23:30:05,284 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
WARNING 2018-10-25 23:30:11,752 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
WARNING 2018-10-25 23:30:22,406 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
WARNING 2018-10-25 23:30:23,774 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
INFO 2018-10-25 23:34:12,783 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
WARNING 2018-10-25 23:34:13,387 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
WARNING 2018-10-25 23:34:19,316 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
WARNING 2018-10-25 23:34:20,155 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
WARNING 2018-10-25 23:34:20,304 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
WARNING 2018-10-25 23:34:20,407 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
WARNING 2018-10-25 23:34:20,567 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
WARNING 2018-10-25 23:34:20,734 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
WARNING 2018-10-25 23:34:20,889 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
WARNING 2018-10-25 23:34:41,309 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
INFO 2018-10-25 23:36:23,018 basehttp 124 "GET /image_codes/eef291f2-0818-4897-8756-bebbdb372878/ HTTP/1.1" 200 3221
INFO 2018-10-25 23:36:29,065 basehttp 124 "GET /usernames/admin/count/ HTTP/1.1" 200 30
INFO 2018-10-25 23:36:41,564 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 204
WARNING 2018-10-25 23:38:36,787 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
WARNING 2018-10-25 23:38:42,346 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
INFO 2018-10-26 08:21:41,368 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
WARNING 2018-10-26 08:21:41,536 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
WARNING 2018-10-26 08:21:46,157 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
WARNING 2018-10-26 08:21:50,418 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
WARNING 2018-10-26 08:22:11,039 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
WARNING 2018-10-26 08:22:17,743 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
WARNING 2018-10-26 08:23:05,637 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
INFO 2018-10-26 08:23:09,542 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 204
INFO 2018-10-26 08:52:05,033 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
WARNING 2018-10-26 08:52:06,354 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
WARNING 2018-10-26 08:52:11,305 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
WARNING 2018-10-26 08:52:21,991 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
INFO 2018-10-26 10:04:33,317 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
WARNING 2018-10-26 10:04:33,594 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
INFO 2018-10-26 10:04:50,030 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 204
INFO 2018-10-26 10:05:19,433 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 204
INFO 2018-10-26 12:35:55,057 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 200 195
INFO 2018-10-26 12:36:26,276 basehttp 124 "GET /oauth/qq/user/?code=394E2FE296882DA79ED4492C0EA00815 HTTP/1.1" 200 190
INFO 2018-10-26 12:36:26,452 basehttp 124 "GET /image_codes/1a2fd7bb-9dbe-45ac-a630-872291347bc5/ HTTP/1.1" 200 3221
INFO 2018-10-26 12:36:52,672 basehttp 124 "GET /image_codes/5cb3f6ef-63b3-4b48-ba70-0bd15a2f4526/ HTTP/1.1" 200 3280
INFO 2018-10-26 12:36:56,991 basehttp 124 "GET /sms_codes/13265942772/?text=5btk&image_code_id=5cb3f6ef-63b3-4b48-ba70-0bd15a2f4526 HTTP/1.1" 200 16
INFO 2018-10-26 12:37:11,821 basehttp 124 "OPTIONS /oauth/qq/user/ HTTP/1.1" 200 0
ERROR 2018-10-26 12:37:11,866 exception 135 Internal Server Error: /oauth/qq/user/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/python/PycharmProjects/meiduo_sz/meiduo/meiduo/apps/oauth/views.py", line 86, in post
    serializer.is_valid(raise_exception=True)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/serializers.py", line 236, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/serializers.py", line 437, in run_validation
    value = self.validate(value)
  File "/home/python/PycharmProjects/meiduo_sz/meiduo/meiduo/apps/oauth/serializers.py", line 32, in validate
    redis_conn = get_redis_connection('verify_codes')
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django_redis/__init__.py", line 14, in get_redis_connection
    cache = caches[alias]
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/cache/__init__.py", line 77, in __getitem__
    "Could not find config for '%s' in settings.CACHES" % alias
django.core.cache.backends.base.InvalidCacheBackendError: Could not find config for 'verify_codes' in settings.CACHES
ERROR 2018-10-26 12:37:12,138 basehttp 124 "POST /oauth/qq/user/ HTTP/1.1" 500 18813
ERROR 2018-10-26 12:37:17,853 exception 135 Internal Server Error: /oauth/qq/user/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/python/PycharmProjects/meiduo_sz/meiduo/meiduo/apps/oauth/views.py", line 86, in post
    serializer.is_valid(raise_exception=True)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/serializers.py", line 236, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/serializers.py", line 437, in run_validation
    value = self.validate(value)
  File "/home/python/PycharmProjects/meiduo_sz/meiduo/meiduo/apps/oauth/serializers.py", line 32, in validate
    redis_conn = get_redis_connection('verify_codes')
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django_redis/__init__.py", line 14, in get_redis_connection
    cache = caches[alias]
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/cache/__init__.py", line 77, in __getitem__
    "Could not find config for '%s' in settings.CACHES" % alias
django.core.cache.backends.base.InvalidCacheBackendError: Could not find config for 'verify_codes' in settings.CACHES
ERROR 2018-10-26 12:37:17,879 basehttp 124 "POST /oauth/qq/user/ HTTP/1.1" 500 18813
ERROR 2018-10-26 12:37:24,031 exception 135 Internal Server Error: /oauth/qq/user/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/python/PycharmProjects/meiduo_sz/meiduo/meiduo/apps/oauth/views.py", line 86, in post
    serializer.is_valid(raise_exception=True)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/serializers.py", line 236, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/serializers.py", line 437, in run_validation
    value = self.validate(value)
  File "/home/python/PycharmProjects/meiduo_sz/meiduo/meiduo/apps/oauth/serializers.py", line 32, in validate
    redis_conn = get_redis_connection('verify_codes')
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django_redis/__init__.py", line 14, in get_redis_connection
    cache = caches[alias]
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/cache/__init__.py", line 77, in __getitem__
    "Could not find config for '%s' in settings.CACHES" % alias
django.core.cache.backends.base.InvalidCacheBackendError: Could not find config for 'verify_codes' in settings.CACHES
ERROR 2018-10-26 12:37:24,057 basehttp 124 "POST /oauth/qq/user/ HTTP/1.1" 500 18813
ERROR 2018-10-26 12:37:24,203 exception 135 Internal Server Error: /oauth/qq/user/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/python/PycharmProjects/meiduo_sz/meiduo/meiduo/apps/oauth/views.py", line 86, in post
    serializer.is_valid(raise_exception=True)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/serializers.py", line 236, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/serializers.py", line 437, in run_validation
    value = self.validate(value)
  File "/home/python/PycharmProjects/meiduo_sz/meiduo/meiduo/apps/oauth/serializers.py", line 32, in validate
    redis_conn = get_redis_connection('verify_codes')
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django_redis/__init__.py", line 14, in get_redis_connection
    cache = caches[alias]
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/cache/__init__.py", line 77, in __getitem__
    "Could not find config for '%s' in settings.CACHES" % alias
django.core.cache.backends.base.InvalidCacheBackendError: Could not find config for 'verify_codes' in settings.CACHES
ERROR 2018-10-26 12:37:25,310 exception 135 Internal Server Error: /oauth/qq/user/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/python/PycharmProjects/meiduo_sz/meiduo/meiduo/apps/oauth/views.py", line 86, in post
    serializer.is_valid(raise_exception=True)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/serializers.py", line 236, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/serializers.py", line 437, in run_validation
    value = self.validate(value)
  File "/home/python/PycharmProjects/meiduo_sz/meiduo/meiduo/apps/oauth/serializers.py", line 32, in validate
    redis_conn = get_redis_connection('verify_codes')
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django_redis/__init__.py", line 14, in get_redis_connection
    cache = caches[alias]
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/cache/__init__.py", line 77, in __getitem__
    "Could not find config for '%s' in settings.CACHES" % alias
django.core.cache.backends.base.InvalidCacheBackendError: Could not find config for 'verify_codes' in settings.CACHES
ERROR 2018-10-26 12:37:25,317 exception 135 Internal Server Error: /oauth/qq/user/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/python/PycharmProjects/meiduo_sz/meiduo/meiduo/apps/oauth/views.py", line 86, in post
    serializer.is_valid(raise_exception=True)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/serializers.py", line 236, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/serializers.py", line 437, in run_validation
    value = self.validate(value)
  File "/home/python/PycharmProjects/meiduo_sz/meiduo/meiduo/apps/oauth/serializers.py", line 32, in validate
    redis_conn = get_redis_connection('verify_codes')
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django_redis/__init__.py", line 14, in get_redis_connection
    cache = caches[alias]
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/cache/__init__.py", line 77, in __getitem__
    "Could not find config for '%s' in settings.CACHES" % alias
django.core.cache.backends.base.InvalidCacheBackendError: Could not find config for 'verify_codes' in settings.CACHES
ERROR 2018-10-26 12:37:25,320 exception 135 Internal Server Error: /oauth/qq/user/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/python/PycharmProjects/meiduo_sz/meiduo/meiduo/apps/oauth/views.py", line 86, in post
    serializer.is_valid(raise_exception=True)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/serializers.py", line 236, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/serializers.py", line 437, in run_validation
    value = self.validate(value)
  File "/home/python/PycharmProjects/meiduo_sz/meiduo/meiduo/apps/oauth/serializers.py", line 32, in validate
    redis_conn = get_redis_connection('verify_codes')
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django_redis/__init__.py", line 14, in get_redis_connection
    cache = caches[alias]
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/cache/__init__.py", line 77, in __getitem__
    "Could not find config for '%s' in settings.CACHES" % alias
django.core.cache.backends.base.InvalidCacheBackendError: Could not find config for 'verify_codes' in settings.CACHES
ERROR 2018-10-26 12:37:25,325 exception 135 Internal Server Error: /oauth/qq/user/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/python/PycharmProjects/meiduo_sz/meiduo/meiduo/apps/oauth/views.py", line 86, in post
    serializer.is_valid(raise_exception=True)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/serializers.py", line 236, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/serializers.py", line 437, in run_validation
    value = self.validate(value)
  File "/home/python/PycharmProjects/meiduo_sz/meiduo/meiduo/apps/oauth/serializers.py", line 32, in validate
    redis_conn = get_redis_connection('verify_codes')
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django_redis/__init__.py", line 14, in get_redis_connection
    cache = caches[alias]
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/cache/__init__.py", line 77, in __getitem__
    "Could not find config for '%s' in settings.CACHES" % alias
django.core.cache.backends.base.InvalidCacheBackendError: Could not find config for 'verify_codes' in settings.CACHES
ERROR 2018-10-26 12:37:25,330 exception 135 Internal Server Error: /oauth/qq/user/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/python/PycharmProjects/meiduo_sz/meiduo/meiduo/apps/oauth/views.py", line 86, in post
    serializer.is_valid(raise_exception=True)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/serializers.py", line 236, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/serializers.py", line 437, in run_validation
    value = self.validate(value)
  File "/home/python/PycharmProjects/meiduo_sz/meiduo/meiduo/apps/oauth/serializers.py", line 32, in validate
    redis_conn = get_redis_connection('verify_codes')
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django_redis/__init__.py", line 14, in get_redis_connection
    cache = caches[alias]
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/cache/__init__.py", line 77, in __getitem__
    "Could not find config for '%s' in settings.CACHES" % alias
django.core.cache.backends.base.InvalidCacheBackendError: Could not find config for 'verify_codes' in settings.CACHES
ERROR 2018-10-26 12:37:25,491 basehttp 124 "POST /oauth/qq/user/ HTTP/1.1" 500 18814
ERROR 2018-10-26 12:37:25,496 exception 135 Internal Server Error: /oauth/qq/user/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/python/PycharmProjects/meiduo_sz/meiduo/meiduo/apps/oauth/views.py", line 86, in post
    serializer.is_valid(raise_exception=True)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/serializers.py", line 236, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/serializers.py", line 437, in run_validation
    value = self.validate(value)
  File "/home/python/PycharmProjects/meiduo_sz/meiduo/meiduo/apps/oauth/serializers.py", line 32, in validate
    redis_conn = get_redis_connection('verify_codes')
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django_redis/__init__.py", line 14, in get_redis_connection
    cache = caches[alias]
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/cache/__init__.py", line 77, in __getitem__
    "Could not find config for '%s' in settings.CACHES" % alias
django.core.cache.backends.base.InvalidCacheBackendError: Could not find config for 'verify_codes' in settings.CACHES
ERROR 2018-10-26 12:37:25,497 basehttp 124 "POST /oauth/qq/user/ HTTP/1.1" 500 18814
ERROR 2018-10-26 12:37:25,512 exception 135 Internal Server Error: /oauth/qq/user/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/python/PycharmProjects/meiduo_sz/meiduo/meiduo/apps/oauth/views.py", line 86, in post
    serializer.is_valid(raise_exception=True)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/serializers.py", line 236, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/serializers.py", line 437, in run_validation
    value = self.validate(value)
  File "/home/python/PycharmProjects/meiduo_sz/meiduo/meiduo/apps/oauth/serializers.py", line 32, in validate
    redis_conn = get_redis_connection('verify_codes')
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django_redis/__init__.py", line 14, in get_redis_connection
    cache = caches[alias]
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/cache/__init__.py", line 77, in __getitem__
    "Could not find config for '%s' in settings.CACHES" % alias
django.core.cache.backends.base.InvalidCacheBackendError: Could not find config for 'verify_codes' in settings.CACHES
ERROR 2018-10-26 12:37:25,521 basehttp 124 "POST /oauth/qq/user/ HTTP/1.1" 500 18814
ERROR 2018-10-26 12:37:25,522 basehttp 124 "POST /oauth/qq/user/ HTTP/1.1" 500 18813
ERROR 2018-10-26 12:37:25,535 basehttp 124 "POST /oauth/qq/user/ HTTP/1.1" 500 18814
ERROR 2018-10-26 12:37:25,539 basehttp 124 "POST /oauth/qq/user/ HTTP/1.1" 500 18813
ERROR 2018-10-26 12:37:25,613 basehttp 124 "POST /oauth/qq/user/ HTTP/1.1" 500 18814
ERROR 2018-10-26 12:37:25,627 basehttp 124 "POST /oauth/qq/user/ HTTP/1.1" 500 18814
ERROR 2018-10-26 12:37:28,307 exception 135 Internal Server Error: /oauth/qq/user/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/python/PycharmProjects/meiduo_sz/meiduo/meiduo/apps/oauth/views.py", line 86, in post
    serializer.is_valid(raise_exception=True)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/serializers.py", line 236, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/serializers.py", line 437, in run_validation
    value = self.validate(value)
  File "/home/python/PycharmProjects/meiduo_sz/meiduo/meiduo/apps/oauth/serializers.py", line 32, in validate
    redis_conn = get_redis_connection('verify_codes')
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django_redis/__init__.py", line 14, in get_redis_connection
    cache = caches[alias]
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/cache/__init__.py", line 77, in __getitem__
    "Could not find config for '%s' in settings.CACHES" % alias
django.core.cache.backends.base.InvalidCacheBackendError: Could not find config for 'verify_codes' in settings.CACHES
ERROR 2018-10-26 12:37:28,332 basehttp 124 "POST /oauth/qq/user/ HTTP/1.1" 500 18813
INFO 2018-10-26 12:39:22,032 basehttp 124 "POST /oauth/qq/user/ HTTP/1.1" 200 218
INFO 2018-10-26 16:39:03,709 basehttp 124 "GET /image_codes/f713714a-9d77-4c3f-813a-2dbf4baa90b5/ HTTP/1.1" 200 3704
INFO 2018-10-26 16:39:09,280 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
WARNING 2018-10-26 16:39:10,036 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
INFO 2018-10-26 16:39:12,962 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 204
INFO 2018-10-26 16:39:20,882 basehttp 124 "OPTIONS /addresses/ HTTP/1.1" 200 0
WARNING 2018-10-26 16:39:21,096 base 152 Not Found: /addresses/
WARNING 2018-10-26 16:39:21,097 basehttp 124 "GET /addresses/ HTTP/1.1" 404 4818
INFO 2018-10-26 16:39:21,194 basehttp 124 "GET /areas/ HTTP/1.1" 200 1204
WARNING 2018-10-26 16:39:23,020 base 152 Not Found: /addresses/
WARNING 2018-10-26 16:39:23,021 basehttp 124 "GET /addresses/ HTTP/1.1" 404 4818
INFO 2018-10-26 16:39:23,023 basehttp 124 "GET /areas/ HTTP/1.1" 200 1204
INFO 2018-10-26 16:40:22,773 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 204
INFO 2018-10-26 16:57:18,055 basehttp 124 "OPTIONS /addresses/ HTTP/1.1" 200 0
WARNING 2018-10-26 16:57:18,523 base 152 Not Found: /addresses/
WARNING 2018-10-26 16:57:18,533 basehttp 124 "GET /addresses/ HTTP/1.1" 404 4818
INFO 2018-10-26 16:57:18,616 basehttp 124 "GET /areas/ HTTP/1.1" 200 1204
INFO 2018-10-26 16:57:36,665 basehttp 124 "GET /areas/110000/ HTTP/1.1" 200 74
INFO 2018-10-26 16:57:40,022 basehttp 124 "GET /areas/110100/ HTTP/1.1" 200 575
WARNING 2018-10-26 16:59:11,889 base 152 Not Found: /addresses/
WARNING 2018-10-26 16:59:11,889 basehttp 124 "POST /addresses/ HTTP/1.1" 404 4819
WARNING 2018-10-26 16:59:15,552 base 152 Not Found: /addresses/
WARNING 2018-10-26 16:59:15,552 basehttp 124 "POST /addresses/ HTTP/1.1" 404 4819
WARNING 2018-10-26 17:00:05,821 base 152 Not Found: /addresses/
WARNING 2018-10-26 17:00:05,830 basehttp 124 "POST /addresses/ HTTP/1.1" 404 4819
WARNING 2018-10-26 17:00:06,522 base 152 Not Found: /addresses/
WARNING 2018-10-26 17:00:06,523 basehttp 124 "POST /addresses/ HTTP/1.1" 404 4819
WARNING 2018-10-26 17:00:06,680 base 152 Not Found: /addresses/
WARNING 2018-10-26 17:00:06,680 basehttp 124 "POST /addresses/ HTTP/1.1" 404 4819
WARNING 2018-10-26 17:00:06,825 base 152 Not Found: /addresses/
WARNING 2018-10-26 17:00:06,825 basehttp 124 "POST /addresses/ HTTP/1.1" 404 4819
WARNING 2018-10-26 17:00:06,986 base 152 Not Found: /addresses/
WARNING 2018-10-26 17:00:06,986 basehttp 124 "POST /addresses/ HTTP/1.1" 404 4819
WARNING 2018-10-26 17:00:23,030 base 152 Not Found: /addresses/
WARNING 2018-10-26 17:00:23,033 basehttp 124 "POST /addresses/ HTTP/1.1" 404 4819
WARNING 2018-10-26 17:00:32,707 base 152 Not Found: /addresses/
WARNING 2018-10-26 17:00:32,707 basehttp 124 "POST /addresses/ HTTP/1.1" 404 4819
WARNING 2018-10-26 17:02:09,869 base 152 Not Found: /addresses/
WARNING 2018-10-26 17:02:09,874 basehttp 124 "POST /addresses/ HTTP/1.1" 404 4819
INFO 2018-10-26 17:07:34,854 basehttp 124 "OPTIONS /addresses/ HTTP/1.1" 200 0
WARNING 2018-10-26 17:07:35,087 base 152 Not Found: /addresses/
WARNING 2018-10-26 17:07:35,126 basehttp 124 "POST /addresses/ HTTP/1.1" 404 4819
INFO 2018-10-26 17:19:49,543 basehttp 124 "OPTIONS /addresses/ HTTP/1.1" 200 0
INFO 2018-10-26 17:19:50,973 basehttp 124 "OPTIONS /addresses/ HTTP/1.1" 200 0
WARNING 2018-10-26 17:19:51,261 base 152 Not Found: /addresses/
WARNING 2018-10-26 17:19:51,338 basehttp 124 "GET /addresses/ HTTP/1.1" 404 4818
INFO 2018-10-26 17:19:51,822 basehttp 124 "GET /areas/ HTTP/1.1" 200 1204
INFO 2018-10-26 17:20:11,505 basehttp 124 "GET /areas/130000/ HTTP/1.1" 200 464
INFO 2018-10-26 17:20:12,584 basehttp 124 "GET /areas/130200/ HTTP/1.1" 200 503
WARNING 2018-10-26 17:20:41,778 base 152 Not Found: /addresses/
WARNING 2018-10-26 17:20:41,778 basehttp 124 "POST /addresses/ HTTP/1.1" 404 4819
WARNING 2018-10-26 17:20:46,366 base 152 Not Found: /addresses/
WARNING 2018-10-26 17:20:46,367 basehttp 124 "POST /addresses/ HTTP/1.1" 404 4819
INFO 2018-10-26 17:21:12,443 basehttp 124 "GET /areas/ HTTP/1.1" 200 1204
WARNING 2018-10-26 17:21:12,488 base 152 Not Found: /addresses/
WARNING 2018-10-26 17:21:12,490 basehttp 124 "GET /addresses/ HTTP/1.1" 404 4818
INFO 2018-10-26 17:21:29,483 basehttp 124 "GET /areas/140000/ HTTP/1.1" 200 404
INFO 2018-10-26 17:21:32,564 basehttp 124 "GET /areas/140400/ HTTP/1.1" 200 461
WARNING 2018-10-26 17:21:56,090 base 152 Not Found: /addresses/
WARNING 2018-10-26 17:21:56,091 basehttp 124 "POST /addresses/ HTTP/1.1" 404 4819
WARNING 2018-10-26 17:22:17,588 base 152 Not Found: /addresses/
WARNING 2018-10-26 17:22:17,590 basehttp 124 "POST /addresses/ HTTP/1.1" 404 4819
WARNING 2018-10-26 17:23:56,611 base 152 Not Found: /addresses/
WARNING 2018-10-26 17:23:56,643 basehttp 124 "POST /addresses/ HTTP/1.1" 404 4819
INFO 2018-10-26 17:25:02,496 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2018-10-26 17:25:03,723 basehttp 124 "GET /user/ HTTP/1.1" 200 82
WARNING 2018-10-26 17:25:16,048 base 152 Not Found: /addresses/
INFO 2018-10-26 17:25:16,048 basehttp 124 "GET /areas/ HTTP/1.1" 200 1204
WARNING 2018-10-26 17:25:16,051 basehttp 124 "GET /addresses/ HTTP/1.1" 404 4818
INFO 2018-10-26 17:25:20,311 basehttp 124 "GET /areas/ HTTP/1.1" 200 1204
WARNING 2018-10-26 17:25:20,325 base 152 Not Found: /addresses/
WARNING 2018-10-26 17:25:20,326 basehttp 124 "GET /addresses/ HTTP/1.1" 404 4818
INFO 2018-10-26 17:25:21,529 basehttp 124 "GET /user/ HTTP/1.1" 200 82
INFO 2018-10-26 18:48:07,619 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2018-10-26 18:48:08,093 basehttp 124 "GET /user/ HTTP/1.1" 200 82
INFO 2018-10-26 18:48:25,365 basehttp 124 "OPTIONS /addresses/ HTTP/1.1" 200 0
INFO 2018-10-26 18:48:25,495 basehttp 124 "GET /areas/ HTTP/1.1" 200 1204
INFO 2018-10-26 18:48:25,513 basehttp 124 "GET /addresses/ HTTP/1.1" 200 65
INFO 2018-10-26 18:48:35,331 basehttp 124 "GET /areas/120000/ HTTP/1.1" 200 74
INFO 2018-10-26 18:48:36,530 basehttp 124 "GET /areas/120100/ HTTP/1.1" 200 572
INFO 2018-10-26 18:49:25,910 basehttp 124 "POST /addresses/ HTTP/1.1" 201 265
INFO 2018-10-26 18:49:36,537 basehttp 124 "GET /user/ HTTP/1.1" 200 82
INFO 2018-10-26 20:18:09,521 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
WARNING 2018-10-26 20:18:09,789 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
WARNING 2018-10-26 20:18:11,419 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
WARNING 2018-10-26 20:18:17,216 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
INFO 2018-10-26 20:18:19,088 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 204
INFO 2018-10-26 20:59:32,303 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
WARNING 2018-10-26 20:59:35,417 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
WARNING 2018-10-26 20:59:35,419 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
INFO 2018-10-26 20:59:42,016 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 204
INFO 2018-10-26 21:06:56,261 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2018-10-26 21:06:57,749 basehttp 124 "GET /user/ HTTP/1.1" 200 82
INFO 2018-10-26 21:06:57,770 basehttp 124 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
INFO 2018-10-26 21:07:39,204 basehttp 124 "OPTIONS /addresses/ HTTP/1.1" 200 0
INFO 2018-10-26 21:07:39,811 basehttp 124 "GET /areas/ HTTP/1.1" 200 1204
INFO 2018-10-26 21:07:39,829 basehttp 124 "GET /addresses/ HTTP/1.1" 200 330
ERROR 2018-10-26 21:07:39,994 exceptions 25 [<users.views.UserBrowseHistoryView object at 0x7f26e04019e8>] Error 111 connecting to 192.168.103.132:6379. Connection refused.
ERROR 2018-10-26 21:07:39,995 basehttp 124 "GET /browse_histories/ HTTP/1.1" 507 35
INFO 2018-10-26 21:07:44,223 basehttp 124 "GET /areas/ HTTP/1.1" 200 1204
INFO 2018-10-26 21:07:44,290 basehttp 124 "GET /addresses/ HTTP/1.1" 200 330
INFO 2018-10-26 21:07:45,484 basehttp 124 "GET /user/ HTTP/1.1" 200 82
INFO 2018-10-26 21:07:52,508 basehttp 124 "GET /areas/ HTTP/1.1" 200 1204
INFO 2018-10-26 21:07:52,620 basehttp 124 "GET /addresses/ HTTP/1.1" 200 330
INFO 2018-10-26 21:07:55,567 basehttp 124 "GET /areas/ HTTP/1.1" 200 1204
INFO 2018-10-26 21:07:55,643 basehttp 124 "GET /addresses/ HTTP/1.1" 200 330
ERROR 2018-10-26 21:08:27,575 exceptions 25 [<users.views.UserBrowseHistoryView object at 0x7f26e01236a0>] Error 111 connecting to 192.168.103.132:6379. Connection refused.
ERROR 2018-10-26 21:08:27,592 basehttp 124 "GET /browse_histories/ HTTP/1.1" 507 35
INFO 2018-10-26 21:09:12,185 basehttp 124 "GET /user/ HTTP/1.1" 200 82
ERROR 2018-10-26 21:09:54,296 exceptions 25 [<users.views.UserBrowseHistoryView object at 0x7f26e017b1d0>] Error 111 connecting to 192.168.103.132:6379. Connection refused.
ERROR 2018-10-26 21:09:54,298 basehttp 124 "GET /browse_histories/ HTTP/1.1" 507 35
INFO 2018-10-26 21:14:37,880 basehttp 124 "GET /user/ HTTP/1.1" 200 82
ERROR 2018-10-26 21:15:19,955 exceptions 25 [<users.views.UserBrowseHistoryView object at 0x7f26e017b3c8>] Error 111 connecting to 192.168.103.132:6379. Connection refused.
ERROR 2018-10-26 21:15:19,971 basehttp 124 "GET /browse_histories/ HTTP/1.1" 507 35
INFO 2018-10-26 21:30:42,130 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2018-10-26 21:30:46,384 base 152 Not Found: /categories/115/
WARNING 2018-10-26 21:30:46,403 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 9171
ERROR 2018-10-26 21:30:46,707 exception 135 Internal Server Error: /cart/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 485, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 400, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
INFO 2018-10-26 21:30:46,746 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 3227
ERROR 2018-10-26 21:30:47,050 basehttp 124 "GET /cart/ HTTP/1.1" 500 90991
WARNING 2018-10-26 21:31:14,545 base 152 Not Found: /categories/115/
WARNING 2018-10-26 21:31:14,550 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 9171
ERROR 2018-10-26 21:31:14,725 exception 135 Internal Server Error: /cart/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 485, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 400, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
INFO 2018-10-26 21:31:14,820 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 3227
ERROR 2018-10-26 21:31:14,971 basehttp 124 "GET /cart/ HTTP/1.1" 500 91126
ERROR 2018-10-26 21:31:21,119 exception 135 Internal Server Error: /cart/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 485, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 400, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR 2018-10-26 21:31:21,228 basehttp 124 "GET /cart/ HTTP/1.1" 500 90991
WARNING 2018-10-26 21:31:43,605 base 152 Not Found: /categories/115/
WARNING 2018-10-26 21:31:43,684 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 9171
ERROR 2018-10-26 21:31:44,060 exception 135 Internal Server Error: /cart/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 485, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 400, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
INFO 2018-10-26 21:31:44,344 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 3227
ERROR 2018-10-26 21:31:44,483 basehttp 124 "GET /cart/ HTTP/1.1" 500 91126
WARNING 2018-10-26 21:31:54,289 base 152 Not Found: /categories/115/
WARNING 2018-10-26 21:31:54,294 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 9171
ERROR 2018-10-26 21:31:54,481 exception 135 Internal Server Error: /cart/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 485, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 400, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
INFO 2018-10-26 21:31:54,559 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 3227
ERROR 2018-10-26 21:31:54,878 basehttp 124 "GET /cart/ HTTP/1.1" 500 91126
ERROR 2018-10-26 21:31:57,147 exception 135 Internal Server Error: /cart/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 485, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 400, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR 2018-10-26 21:31:57,260 basehttp 124 "GET /cart/ HTTP/1.1" 500 90991
INFO 2018-10-26 21:33:41,566 basehttp 124 "GET /categories/115/skus/?page=2&page_size=5&ordering=-create_time HTTP/1.1" 200 3227
INFO 2018-10-26 21:33:42,721 basehttp 124 "GET /categories/115/skus/?page=3&page_size=5&ordering=-create_time HTTP/1.1" 200 3227
INFO 2018-10-26 21:33:44,391 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 3227
INFO 2018-10-26 21:33:45,086 basehttp 124 "GET /categories/115/skus/?page=2&page_size=5&ordering=-create_time HTTP/1.1" 200 3227
INFO 2018-10-26 21:33:45,841 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 3227
INFO 2018-10-26 21:33:54,373 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 3227
ERROR 2018-10-26 21:33:54,421 exception 135 Internal Server Error: /cart/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 485, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 400, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
WARNING 2018-10-26 21:33:54,547 base 152 Not Found: /categories/115/
WARNING 2018-10-26 21:33:54,548 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 9171
ERROR 2018-10-26 21:33:54,796 basehttp 124 "GET /cart/ HTTP/1.1" 500 91126
WARNING 2018-10-26 21:37:46,706 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-10-26 21:37:46,718 base 152 Not Found: /categories/115/
WARNING 2018-10-26 21:37:46,815 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 9171
WARNING 2018-10-26 21:37:46,828 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 9195
ERROR 2018-10-26 21:37:47,477 exception 135 Internal Server Error: /cart/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 485, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 400, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
INFO 2018-10-26 21:37:47,620 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 3227
ERROR 2018-10-26 21:37:48,114 basehttp 124 "GET /cart/ HTTP/1.1" 500 91126
WARNING 2018-10-26 21:37:59,040 base 152 Not Found: /categories/115/
WARNING 2018-10-26 21:37:59,104 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-10-26 21:37:59,120 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 9195
WARNING 2018-10-26 21:37:59,108 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 9171
ERROR 2018-10-26 21:37:59,371 exception 135 Internal Server Error: /cart/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 485, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 400, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
INFO 2018-10-26 21:37:59,526 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 3227
ERROR 2018-10-26 21:37:59,643 basehttp 124 "GET /cart/ HTTP/1.1" 500 91126
WARNING 2018-10-26 21:38:34,917 base 152 Not Found: /categories/115/
WARNING 2018-10-26 21:38:34,935 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 9171
WARNING 2018-10-26 21:38:34,950 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-10-26 21:38:34,954 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 9195
ERROR 2018-10-26 21:38:34,977 exception 135 Internal Server Error: /cart/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 485, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 400, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
INFO 2018-10-26 21:38:35,021 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 3227
ERROR 2018-10-26 21:38:35,116 basehttp 124 "GET /cart/ HTTP/1.1" 500 90991
INFO 2018-10-26 21:44:03,056 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 3227
INFO 2018-10-26 21:44:03,061 basehttp 124 "GET /categories/115/skus/?page=2&page_size=5&ordering=-create_time HTTP/1.1" 200 3227
INFO 2018-10-26 21:44:03,044 basehttp 124 "GET /categories/115/skus/?page=4&page_size=5&ordering=-create_time HTTP/1.1" 200 3227
INFO 2018-10-26 21:44:03,065 basehttp 124 "GET /categories/115/skus/?page=3&page_size=5&ordering=-create_time HTTP/1.1" 200 3227
INFO 2018-10-26 21:44:03,141 basehttp 124 "GET /categories/115/skus/?page=6&page_size=5&ordering=-create_time HTTP/1.1" 200 3227
INFO 2018-10-26 21:44:03,676 basehttp 124 "GET /categories/115/skus/?page=7&page_size=5&ordering=-create_time HTTP/1.1" 200 3227
INFO 2018-10-26 21:44:07,405 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2018-10-26 21:44:07,599 base 152 Not Found: /categories/115/
WARNING 2018-10-26 21:44:07,602 base 152 Not Found: /categories/115/hotskus/
INFO 2018-10-26 21:44:07,602 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 3227
WARNING 2018-10-26 21:44:07,603 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 9195
WARNING 2018-10-26 21:44:07,605 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 9171
ERROR 2018-10-26 21:44:07,631 exception 135 Internal Server Error: /cart/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 485, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 400, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR 2018-10-26 21:44:07,778 basehttp 124 "GET /cart/ HTTP/1.1" 500 90991
WARNING 2018-10-26 21:44:10,183 base 152 Not Found: /categories/115/
WARNING 2018-10-26 21:44:10,188 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 9171
WARNING 2018-10-26 21:44:10,206 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-10-26 21:44:10,210 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 9195
INFO 2018-10-26 21:44:10,238 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 3227
ERROR 2018-10-26 21:44:10,243 exception 135 Internal Server Error: /cart/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 485, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 400, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR 2018-10-26 21:44:10,344 basehttp 124 "GET /cart/ HTTP/1.1" 500 90991
WARNING 2018-10-26 21:44:23,645 base 152 Not Found: /categories/119/
WARNING 2018-10-26 21:44:23,655 base 152 Not Found: /categories/119/hotskus/
WARNING 2018-10-26 21:44:23,657 basehttp 124 "GET /categories/119/hotskus/ HTTP/1.1" 404 9195
WARNING 2018-10-26 21:44:23,658 basehttp 124 "GET /categories/119/ HTTP/1.1" 404 9171
INFO 2018-10-26 21:44:23,704 basehttp 124 "GET /categories/119/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 2
ERROR 2018-10-26 21:44:23,710 exception 135 Internal Server Error: /cart/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 485, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 400, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR 2018-10-26 21:44:23,862 basehttp 124 "GET /cart/ HTTP/1.1" 500 90991
INFO 2018-10-26 22:09:08,797 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2018-10-26 22:09:14,823 base 152 Not Found: /categories/115/
WARNING 2018-10-26 22:09:14,835 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 9171
WARNING 2018-10-26 22:09:14,845 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-10-26 22:09:14,853 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 9195
ERROR 2018-10-26 22:09:15,059 exception 135 Internal Server Error: /cart/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 485, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 400, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
INFO 2018-10-26 22:09:15,100 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 3227
ERROR 2018-10-26 22:09:15,277 basehttp 124 "GET /cart/ HTTP/1.1" 500 90974
WARNING 2018-10-26 22:13:02,966 base 152 Not Found: /categories/115/
WARNING 2018-10-26 22:13:02,979 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-10-26 22:13:03,311 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 9195
WARNING 2018-10-26 22:13:03,317 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 9171
ERROR 2018-10-26 22:13:03,827 exception 135 Internal Server Error: /cart/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 485, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 400, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
INFO 2018-10-26 22:13:04,088 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 3227
ERROR 2018-10-26 22:13:04,316 basehttp 124 "GET /cart/ HTTP/1.1" 500 91108
INFO 2018-10-26 22:21:32,004 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2018-10-26 22:21:32,474 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-10-26 22:21:32,488 base 152 Not Found: /categories/115/
WARNING 2018-10-26 22:21:32,523 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 9171
WARNING 2018-10-26 22:21:32,597 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 9195
ERROR 2018-10-26 22:21:32,855 exception 135 Internal Server Error: /cart/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 485, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 400, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
INFO 2018-10-26 22:21:33,041 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 3227
ERROR 2018-10-26 22:21:33,213 basehttp 124 "GET /cart/ HTTP/1.1" 500 90974
INFO 2018-10-26 22:21:35,271 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=price HTTP/1.1" 200 3227
INFO 2018-10-26 22:21:36,240 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=sales HTTP/1.1" 200 3227
INFO 2018-10-26 22:21:36,800 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=price HTTP/1.1" 200 3227
INFO 2018-10-26 22:21:37,386 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 3227
INFO 2018-10-26 22:21:46,741 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=price HTTP/1.1" 200 3227
INFO 2018-10-26 22:21:47,245 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=sales HTTP/1.1" 200 3227
WARNING 2018-10-26 22:21:49,245 base 152 Not Found: /categories/115/
WARNING 2018-10-26 22:21:49,253 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 9171
WARNING 2018-10-26 22:21:49,267 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-10-26 22:21:49,268 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 9195
ERROR 2018-10-26 22:21:49,283 exception 135 Internal Server Error: /cart/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 485, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 400, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
INFO 2018-10-26 22:21:49,363 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 3227
ERROR 2018-10-26 22:21:49,563 basehttp 124 "GET /cart/ HTTP/1.1" 500 90973
WARNING 2018-10-26 22:22:15,838 base 152 Not Found: /categories/115/
WARNING 2018-10-26 22:22:15,866 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-10-26 22:22:15,867 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 9171
WARNING 2018-10-26 22:22:15,868 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 9195
ERROR 2018-10-26 22:22:15,905 exception 135 Internal Server Error: /cart/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 485, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 400, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
INFO 2018-10-26 22:22:15,927 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 3227
ERROR 2018-10-26 22:22:15,981 basehttp 124 "GET /cart/ HTTP/1.1" 500 90973
WARNING 2018-10-26 22:29:39,470 base 152 Not Found: /categories/115/
WARNING 2018-10-26 22:29:39,483 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-10-26 22:29:39,490 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 9195
WARNING 2018-10-26 22:29:39,490 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 9171
ERROR 2018-10-26 22:29:39,852 exception 135 Internal Server Error: /cart/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 485, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/python/.virtualenvs/meiduo/lib/python3.5/site-packages/rest_framework/views.py", line 400, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
INFO 2018-10-26 22:29:39,909 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1321
ERROR 2018-10-26 22:29:40,088 basehttp 124 "GET /cart/ HTTP/1.1" 500 91209
INFO 2018-10-26 22:30:08,414 basehttp 124 "GET /categories/115/skus/?page=2&page_size=5&ordering=-create_time HTTP/1.1" 200 1369
INFO 2018-10-26 22:30:10,792 basehttp 124 "GET /categories/115/skus/?page=3&page_size=5&ordering=-create_time HTTP/1.1" 200 1033
INFO 2018-10-26 22:30:12,122 basehttp 124 "GET /categories/115/skus/?page=2&page_size=5&ordering=-create_time HTTP/1.1" 200 1369
INFO 2018-10-26 22:30:13,788 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1321
INFO 2018-10-26 22:30:15,106 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=price HTTP/1.1" 200 1312
INFO 2018-10-26 22:30:18,688 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=sales HTTP/1.1" 200 1270
INFO 2018-10-26 22:30:19,953 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=price HTTP/1.1" 200 1312
INFO 2018-10-26 22:30:20,652 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1321
INFO 2018-10-26 22:30:21,979 basehttp 124 "GET /categories/115/skus/?page=2&page_size=5&ordering=-create_time HTTP/1.1" 200 1369
INFO 2018-10-26 22:30:23,140 basehttp 124 "GET /categories/115/skus/?page=3&page_size=5&ordering=-create_time HTTP/1.1" 200 1033
INFO 2018-10-26 22:30:23,708 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1321
INFO 2018-10-26 22:30:24,473 basehttp 124 "GET /categories/115/skus/?page=2&page_size=5&ordering=-create_time HTTP/1.1" 200 1369
INFO 2018-10-26 22:30:25,328 basehttp 124 "GET /categories/115/skus/?page=3&page_size=5&ordering=-create_time HTTP/1.1" 200 1033
INFO 2018-10-26 22:30:36,190 basehttp 124 "GET /skus/search/?text=%E6%89%8B%E6%9C%BA&page=1&page_size=6 HTTP/1.1" 200 52
INFO 2018-10-26 22:39:30,625 basehttp 124 "GET /skus/search/?text=wifi HTTP/1.1" 200 5399
INFO 2018-10-26 22:39:30,845 basehttp 124 "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121200
INFO 2018-10-26 22:39:30,852 basehttp 124 "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
INFO 2018-10-26 22:39:30,853 basehttp 124 "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
INFO 2018-10-26 22:39:30,862 basehttp 124 "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
INFO 2018-10-26 22:39:30,875 basehttp 124 "GET /static/rest_framework/js/jquery-3.3.1.min.js HTTP/1.1" 200 86927
INFO 2018-10-26 22:39:30,876 basehttp 124 "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
INFO 2018-10-26 22:39:30,883 basehttp 124 "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1735
INFO 2018-10-26 22:39:30,885 basehttp 124 "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
INFO 2018-10-26 22:39:30,887 basehttp 124 "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1262
INFO 2018-10-26 22:39:30,888 basehttp 124 "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 37045
INFO 2018-10-26 22:39:31,428 basehttp 124 "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
WARNING 2018-10-26 22:39:32,069 base 152 Not Found: /favicon.ico
WARNING 2018-10-26 22:39:32,076 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 9159
INFO 2018-10-26 22:54:40,581 basehttp 124 "GET /skus/search/?text=wifi HTTP/1.1" 200 5399
INFO 2018-10-26 22:54:41,644 basehttp 124 "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
INFO 2018-10-26 22:54:41,647 basehttp 124 "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
INFO 2018-10-26 22:54:41,652 basehttp 124 "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
INFO 2018-10-26 22:54:41,657 basehttp 124 "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
INFO 2018-10-26 22:54:41,655 basehttp 124 "GET /static/rest_framework/js/jquery-3.3.1.min.js HTTP/1.1" 304 0
INFO 2018-10-26 22:54:41,656 basehttp 124 "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
INFO 2018-10-26 22:54:41,696 basehttp 124 "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
INFO 2018-10-26 22:54:41,711 basehttp 124 "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
INFO 2018-10-26 22:54:41,712 basehttp 124 "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
INFO 2018-10-26 22:54:41,729 basehttp 124 "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
INFO 2018-10-26 22:54:43,894 basehttp 124 "GET /skus/search/?text=%E6%89%8B%E6%9C%BA&page=1&page_size=6 HTTP/1.1" 200 52
INFO 2018-10-26 23:02:32,218 basehttp 124 "GET /skus/search/?text=%E6%89%8B%E6%9C%BA&page=1&page_size=6 HTTP/1.1" 200 52
INFO 2018-10-26 23:11:06,973 basehttp 124 "GET /skus/search/?text=%E6%89%8B%E6%9C%BA&page=1&page_size=6 HTTP/1.1" 200 52
INFO 2018-10-27 09:53:35,146 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
INFO 2018-10-27 09:53:35,457 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 204
INFO 2018-10-27 09:53:42,786 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
INFO 2018-10-27 09:53:42,965 basehttp 124 "GET /cart/ HTTP/1.1" 200 2
INFO 2018-10-27 09:53:53,110 basehttp 124 "GET /cart/ HTTP/1.1" 200 2
INFO 2018-10-27 09:53:55,892 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2018-10-27 09:53:56,037 basehttp 124 "GET /user/ HTTP/1.1" 200 82
INFO 2018-10-27 09:53:56,045 basehttp 124 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
INFO 2018-10-27 09:53:56,091 basehttp 124 "GET /browse_histories/ HTTP/1.1" 200 2
WARNING 2018-10-27 09:54:08,238 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-10-27 09:54:08,243 base 152 Not Found: /categories/115/
WARNING 2018-10-27 09:54:08,263 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 9339
WARNING 2018-10-27 09:54:08,278 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 9363
INFO 2018-10-27 09:54:08,296 basehttp 124 "GET /cart/ HTTP/1.1" 200 2
INFO 2018-10-27 09:54:08,320 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1321
INFO 2018-10-27 09:54:10,713 basehttp 124 "POST /browse_histories/ HTTP/1.1" 201 13
INFO 2018-10-27 09:54:10,717 basehttp 124 "POST /browse_histories/ HTTP/1.1" 201 13
INFO 2018-10-27 09:54:16,798 basehttp 124 "POST /cart/ HTTP/1.1" 201 39
INFO 2018-10-27 09:54:22,825 basehttp 124 "GET /cart/ HTTP/1.1" 200 250
WARNING 2018-10-27 09:54:49,974 base 152 Not Found: /categories/115/
WARNING 2018-10-27 09:54:50,001 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 9339
WARNING 2018-10-27 09:54:50,034 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-10-27 09:54:50,039 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 9363
INFO 2018-10-27 09:54:50,100 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1321
INFO 2018-10-27 09:54:50,101 basehttp 124 "GET /cart/ HTTP/1.1" 200 250
INFO 2018-10-27 09:55:01,597 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2018-10-27 09:55:01,632 base 152 Not Found: /categories/116/
WARNING 2018-10-27 09:55:01,637 base 152 Not Found: /categories/116/hotskus/
WARNING 2018-10-27 09:55:01,639 basehttp 124 "GET /categories/116/hotskus/ HTTP/1.1" 404 9363
WARNING 2018-10-27 09:55:01,645 basehttp 124 "GET /categories/116/ HTTP/1.1" 404 9339
INFO 2018-10-27 09:55:01,715 basehttp 124 "GET /cart/ HTTP/1.1" 200 2
INFO 2018-10-27 09:55:01,803 basehttp 124 "GET /categories/116/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 52
WARNING 2018-10-27 09:55:07,422 base 152 Not Found: /categories/119/
WARNING 2018-10-27 09:55:07,448 basehttp 124 "GET /categories/119/ HTTP/1.1" 404 9339
WARNING 2018-10-27 09:55:07,473 base 152 Not Found: /categories/119/hotskus/
WARNING 2018-10-27 09:55:07,478 basehttp 124 "GET /categories/119/hotskus/ HTTP/1.1" 404 9363
INFO 2018-10-27 09:55:07,485 basehttp 124 "GET /cart/ HTTP/1.1" 200 2
INFO 2018-10-27 09:55:07,491 basehttp 124 "GET /categories/119/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 52
WARNING 2018-10-27 09:55:11,459 base 152 Not Found: /categories/115/
WARNING 2018-10-27 09:55:11,470 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-10-27 09:55:11,477 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 9339
WARNING 2018-10-27 09:55:11,483 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 9363
INFO 2018-10-27 09:55:11,489 basehttp 124 "GET /cart/ HTTP/1.1" 200 2
INFO 2018-10-27 09:55:11,527 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1321
INFO 2018-10-27 09:55:13,113 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=price HTTP/1.1" 200 1312
INFO 2018-10-27 09:55:13,801 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=sales HTTP/1.1" 200 1270
INFO 2018-10-27 09:55:14,632 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=price HTTP/1.1" 200 1312
INFO 2018-10-27 09:55:14,887 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1321
INFO 2018-10-27 09:55:21,279 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2018-10-27 09:55:21,319 basehttp 124 "POST /cart/ HTTP/1.1" 400 37
INFO 2018-10-27 09:55:30,305 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2018-10-27 09:55:30,324 base 152 Not Found: /categories/115/
WARNING 2018-10-27 09:55:30,341 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 9339
WARNING 2018-10-27 09:55:30,363 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-10-27 09:55:30,364 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 9363
INFO 2018-10-27 09:55:30,407 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1321
INFO 2018-10-27 09:55:30,552 basehttp 124 "GET /cart/ HTTP/1.1" 200 2
INFO 2018-10-27 09:55:36,164 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
INFO 2018-10-27 09:55:36,200 basehttp 124 "POST /cart/ HTTP/1.1" 201 39
INFO 2018-10-27 09:55:45,004 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
INFO 2018-10-27 09:55:45,078 basehttp 124 "POST /cart/ HTTP/1.1" 201 39
INFO 2018-10-27 09:55:52,507 basehttp 124 "GET /cart/ HTTP/1.1" 200 499
INFO 2018-10-27 09:56:22,348 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
INFO 2018-10-27 09:56:22,492 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 204
INFO 2018-10-27 09:56:26,408 basehttp 124 "GET /cart/ HTTP/1.1" 200 499
INFO 2018-10-27 09:56:31,354 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2018-10-27 09:56:31,459 basehttp 124 "GET /user/ HTTP/1.1" 200 82
INFO 2018-10-27 09:56:31,479 basehttp 124 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
INFO 2018-10-27 09:56:31,548 basehttp 124 "GET /browse_histories/ HTTP/1.1" 200 237
INFO 2018-10-27 09:56:36,270 basehttp 124 "OPTIONS /addresses/ HTTP/1.1" 200 0
INFO 2018-10-27 09:56:36,369 basehttp 124 "GET /areas/ HTTP/1.1" 200 1204
INFO 2018-10-27 09:56:36,400 basehttp 124 "GET /addresses/ HTTP/1.1" 200 330
INFO 2018-10-27 09:56:40,411 basehttp 124 "GET /areas/ HTTP/1.1" 200 1204
INFO 2018-10-27 09:56:40,498 basehttp 124 "GET /addresses/ HTTP/1.1" 200 330
INFO 2018-10-27 09:56:43,706 basehttp 124 "GET /user/ HTTP/1.1" 200 82
INFO 2018-10-27 09:56:43,814 basehttp 124 "GET /browse_histories/ HTTP/1.1" 200 237
INFO 2018-10-27 09:56:48,308 basehttp 124 "GET /cart/ HTTP/1.1" 200 499
INFO 2018-10-27 09:57:02,032 basehttp 124 "GET /cart/ HTTP/1.1" 200 499
INFO 2018-10-27 11:21:49,774 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2018-10-27 11:21:50,039 base 152 Not Found: /categories/115/
WARNING 2018-10-27 11:21:50,071 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 9496
WARNING 2018-10-27 11:21:50,074 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-10-27 11:21:50,080 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 9520
INFO 2018-10-27 11:21:50,709 basehttp 124 "GET /cart/ HTTP/1.1" 200 499
INFO 2018-10-27 11:21:50,709 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1321
INFO 2018-10-27 11:22:30,134 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
WARNING 2018-10-27 11:22:30,350 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
INFO 2018-10-27 11:22:34,093 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 204
INFO 2018-10-27 11:26:39,635 basehttp 124 "OPTIONS /orders/?page=1&page_size=5 HTTP/1.1" 200 0
WARNING 2018-10-27 11:26:40,514 basehttp 124 "GET /orders/?page=1&page_size=5 HTTP/1.1" 405 45
WARNING 2018-10-27 11:27:04,199 basehttp 124 "GET /orders/?page=1&page_size=5 HTTP/1.1" 405 45
INFO 2018-10-27 11:27:06,878 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2018-10-27 11:27:07,262 basehttp 124 "GET /user/ HTTP/1.1" 200 82
INFO 2018-10-27 11:27:07,274 basehttp 124 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
INFO 2018-10-27 11:27:07,415 basehttp 124 "GET /browse_histories/ HTTP/1.1" 200 237
INFO 2018-10-27 11:27:08,631 basehttp 124 "OPTIONS /addresses/ HTTP/1.1" 200 0
INFO 2018-10-27 11:27:08,934 basehttp 124 "GET /areas/ HTTP/1.1" 200 1204
INFO 2018-10-27 11:27:08,942 basehttp 124 "GET /addresses/ HTTP/1.1" 200 330
INFO 2018-10-27 11:27:11,070 basehttp 124 "GET /user/ HTTP/1.1" 200 82
INFO 2018-10-27 11:27:11,139 basehttp 124 "GET /browse_histories/ HTTP/1.1" 200 237
INFO 2018-10-27 11:27:13,540 basehttp 124 "POST /browse_histories/ HTTP/1.1" 201 13
INFO 2018-10-27 11:27:13,546 basehttp 124 "POST /browse_histories/ HTTP/1.1" 201 13
INFO 2018-10-27 11:27:16,745 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
INFO 2018-10-27 11:27:16,790 basehttp 124 "POST /cart/ HTTP/1.1" 201 39
WARNING 2018-10-27 11:27:20,758 basehttp 124 "GET /orders/?page=1&page_size=5 HTTP/1.1" 405 45
INFO 2018-10-27 11:27:22,824 basehttp 124 "GET /user/ HTTP/1.1" 200 82
INFO 2018-10-27 11:27:22,897 basehttp 124 "GET /browse_histories/ HTTP/1.1" 200 237
WARNING 2018-10-27 11:27:23,512 basehttp 124 "GET /orders/?page=1&page_size=5 HTTP/1.1" 405 45
INFO 2018-10-27 11:27:25,220 basehttp 124 "GET /user/ HTTP/1.1" 200 82
INFO 2018-10-27 11:27:25,283 basehttp 124 "GET /browse_histories/ HTTP/1.1" 200 237
WARNING 2018-10-27 11:27:26,209 basehttp 124 "GET /orders/?page=1&page_size=5 HTTP/1.1" 405 45
INFO 2018-10-27 11:27:27,439 basehttp 124 "GET /areas/ HTTP/1.1" 200 1204
INFO 2018-10-27 11:27:27,607 basehttp 124 "GET /addresses/ HTTP/1.1" 200 330
INFO 2018-10-27 11:27:29,662 basehttp 124 "GET /user/ HTTP/1.1" 200 82
INFO 2018-10-27 11:27:29,736 basehttp 124 "GET /browse_histories/ HTTP/1.1" 200 237
WARNING 2018-10-27 11:27:31,099 basehttp 124 "GET /orders/?page=1&page_size=5 HTTP/1.1" 405 45
INFO 2018-10-27 11:27:33,692 basehttp 124 "GET /cart/ HTTP/1.1" 200 499
WARNING 2018-10-27 11:33:57,850 basehttp 124 "GET /orders/?page=1&page_size=5 HTTP/1.1" 405 45
INFO 2018-10-27 11:33:58,705 basehttp 124 "GET /user/ HTTP/1.1" 200 82
INFO 2018-10-27 11:33:58,904 basehttp 124 "GET /browse_histories/ HTTP/1.1" 200 237
WARNING 2018-10-27 11:33:59,986 basehttp 124 "GET /orders/?page=1&page_size=5 HTTP/1.1" 405 45
INFO 2018-10-27 11:34:06,908 basehttp 124 "GET /cart/ HTTP/1.1" 200 499
INFO 2018-10-27 11:34:09,558 basehttp 124 "PUT /cart/ HTTP/1.1" 200 40
INFO 2018-10-27 11:34:19,040 basehttp 124 "GET /areas/ HTTP/1.1" 200 1204
INFO 2018-10-27 11:34:19,146 basehttp 124 "GET /addresses/ HTTP/1.1" 200 330
INFO 2018-10-27 11:34:21,558 basehttp 124 "OPTIONS /addresses/1/status/ HTTP/1.1" 200 0
INFO 2018-10-27 11:34:21,747 basehttp 124 "PUT /addresses/1/status/ HTTP/1.1" 200 16
WARNING 2018-10-27 11:34:27,779 basehttp 124 "GET /orders/?page=1&page_size=5 HTTP/1.1" 405 45
INFO 2018-10-27 11:34:28,622 basehttp 124 "GET /user/ HTTP/1.1" 200 82
INFO 2018-10-27 11:34:28,740 basehttp 124 "GET /browse_histories/ HTTP/1.1" 200 237
INFO 2018-10-27 11:34:31,361 basehttp 124 "POST /browse_histories/ HTTP/1.1" 201 13
INFO 2018-10-27 11:34:31,363 basehttp 124 "POST /browse_histories/ HTTP/1.1" 201 13
WARNING 2018-10-27 11:34:33,915 basehttp 124 "GET /orders/?page=1&page_size=5 HTTP/1.1" 405 45
INFO 2018-10-27 11:34:34,961 basehttp 124 "GET /cart/ HTTP/1.1" 200 500
INFO 2018-10-27 11:34:51,047 basehttp 124 "GET /user/ HTTP/1.1" 200 82
INFO 2018-10-27 11:34:51,162 basehttp 124 "GET /browse_histories/ HTTP/1.1" 200 237
INFO 2018-10-27 11:34:54,410 basehttp 124 "GET /cart/ HTTP/1.1" 200 500
WARNING 2018-10-27 11:34:55,307 basehttp 124 "GET /orders/?page=1&page_size=5 HTTP/1.1" 405 45
INFO 2018-10-27 11:36:02,495 basehttp 124 "GET /user/ HTTP/1.1" 200 82
INFO 2018-10-27 11:36:02,584 basehttp 124 "GET /browse_histories/ HTTP/1.1" 200 237
WARNING 2018-10-27 11:36:13,880 base 152 Not Found: /categories/115/
WARNING 2018-10-27 11:36:13,887 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-10-27 11:36:13,888 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 9520
WARNING 2018-10-27 11:36:13,889 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 9496
INFO 2018-10-27 11:36:13,925 basehttp 124 "GET /cart/ HTTP/1.1" 200 500
INFO 2018-10-27 11:36:13,946 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1321
INFO 2018-10-27 11:36:15,423 basehttp 124 "POST /browse_histories/ HTTP/1.1" 201 13
INFO 2018-10-27 11:36:15,430 basehttp 124 "POST /browse_histories/ HTTP/1.1" 201 13
WARNING 2018-10-27 11:36:31,717 base 152 Not Found: /categories/115/
WARNING 2018-10-27 11:36:31,719 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-10-27 11:36:31,722 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 9520
WARNING 2018-10-27 11:36:31,724 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 9496
INFO 2018-10-27 11:36:31,760 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1321
INFO 2018-10-27 11:36:31,775 basehttp 124 "GET /cart/ HTTP/1.1" 200 500
INFO 2018-10-27 11:36:36,797 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=price HTTP/1.1" 200 1312
INFO 2018-10-27 11:36:37,390 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=sales HTTP/1.1" 200 1270
INFO 2018-10-27 11:36:38,928 basehttp 124 "POST /browse_histories/ HTTP/1.1" 201 12
INFO 2018-10-27 11:36:38,937 basehttp 124 "POST /browse_histories/ HTTP/1.1" 201 12
WARNING 2018-10-27 11:36:54,654 base 152 Not Found: /categories/115/
WARNING 2018-10-27 11:36:54,669 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 9496
WARNING 2018-10-27 11:36:54,676 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-10-27 11:36:54,686 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 9520
INFO 2018-10-27 11:36:54,701 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1321
INFO 2018-10-27 11:36:54,708 basehttp 124 "GET /cart/ HTTP/1.1" 200 500
WARNING 2018-10-27 11:37:08,984 base 152 Not Found: /categories/115/
WARNING 2018-10-27 11:37:09,009 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-10-27 11:37:09,011 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 9496
WARNING 2018-10-27 11:37:09,012 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 9520
INFO 2018-10-27 11:37:09,041 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1321
INFO 2018-10-27 11:37:09,055 basehttp 124 "GET /cart/ HTTP/1.1" 200 500
WARNING 2018-10-27 11:37:14,617 base 152 Not Found: /categories/116/
WARNING 2018-10-27 11:37:14,636 basehttp 124 "GET /categories/116/ HTTP/1.1" 404 9496
WARNING 2018-10-27 11:37:14,662 base 152 Not Found: /categories/116/hotskus/
WARNING 2018-10-27 11:37:14,663 basehttp 124 "GET /categories/116/hotskus/ HTTP/1.1" 404 9520
INFO 2018-10-27 11:37:14,683 basehttp 124 "GET /categories/116/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 52
INFO 2018-10-27 11:37:14,691 basehttp 124 "GET /cart/ HTTP/1.1" 200 500
WARNING 2018-10-27 11:37:19,312 base 152 Not Found: /categories/117/hotskus/
INFO 2018-10-27 11:37:19,312 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2018-10-27 11:37:19,320 base 152 Not Found: /categories/117/
WARNING 2018-10-27 11:37:19,341 basehttp 124 "GET /categories/117/ HTTP/1.1" 404 9496
WARNING 2018-10-27 11:37:19,336 basehttp 124 "GET /categories/117/hotskus/ HTTP/1.1" 404 9520
INFO 2018-10-27 11:37:19,378 basehttp 124 "GET /categories/117/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 52
INFO 2018-10-27 11:37:19,402 basehttp 124 "GET /cart/ HTTP/1.1" 200 500
WARNING 2018-10-27 11:37:23,508 base 152 Not Found: /categories/118/
INFO 2018-10-27 11:37:23,550 basehttp 124 "GET /categories/118/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 52
WARNING 2018-10-27 11:37:23,562 base 152 Not Found: /categories/118/hotskus/
WARNING 2018-10-27 11:37:23,572 basehttp 124 "GET /categories/118/hotskus/ HTTP/1.1" 404 9520
WARNING 2018-10-27 11:37:23,573 basehttp 124 "GET /categories/118/ HTTP/1.1" 404 9496
INFO 2018-10-27 11:37:23,597 basehttp 124 "GET /cart/ HTTP/1.1" 200 500
WARNING 2018-10-27 11:37:29,455 base 152 Not Found: /categories/157/
WARNING 2018-10-27 11:37:29,482 base 152 Not Found: /categories/157/hotskus/
WARNING 2018-10-27 11:37:29,486 basehttp 124 "GET /categories/157/hotskus/ HTTP/1.1" 404 9520
WARNING 2018-10-27 11:37:29,488 basehttp 124 "GET /categories/157/ HTTP/1.1" 404 9496
INFO 2018-10-27 11:37:29,568 basehttp 124 "GET /categories/157/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 452
INFO 2018-10-27 11:37:29,570 basehttp 124 "GET /cart/ HTTP/1.1" 200 500
INFO 2018-10-27 11:37:31,941 basehttp 124 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
INFO 2018-10-27 11:37:31,942 basehttp 124 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
INFO 2018-10-27 11:37:32,124 basehttp 124 "POST /browse_histories/ HTTP/1.1" 201 12
INFO 2018-10-27 11:37:32,131 basehttp 124 "POST /browse_histories/ HTTP/1.1" 201 12
INFO 2018-10-27 11:37:37,645 basehttp 124 "POST /browse_histories/ HTTP/1.1" 201 12
INFO 2018-10-27 11:37:37,650 basehttp 124 "POST /browse_histories/ HTTP/1.1" 201 12
INFO 2018-10-27 11:37:58,834 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2018-10-27 11:37:58,911 basehttp 124 "GET /user/ HTTP/1.1" 200 82
INFO 2018-10-27 11:37:58,980 basehttp 124 "GET /browse_histories/ HTTP/1.1" 200 1060
INFO 2018-10-27 11:38:02,710 basehttp 124 "OPTIONS /orders/?page=1&page_size=5 HTTP/1.1" 200 0
WARNING 2018-10-27 11:38:02,811 basehttp 124 "GET /orders/?page=1&page_size=5 HTTP/1.1" 405 45
WARNING 2018-10-27 11:38:21,874 base 152 Not Found: /categories/267/
WARNING 2018-10-27 11:38:21,877 base 152 Not Found: /categories/267/hotskus/
WARNING 2018-10-27 11:38:21,885 basehttp 124 "GET /categories/267/hotskus/ HTTP/1.1" 404 9520
WARNING 2018-10-27 11:38:21,887 basehttp 124 "GET /categories/267/ HTTP/1.1" 404 9496
INFO 2018-10-27 11:38:22,051 basehttp 124 "GET /categories/267/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 52
INFO 2018-10-27 11:38:22,068 basehttp 124 "GET /cart/ HTTP/1.1" 200 500
INFO 2018-10-27 11:39:04,949 basehttp 124 "GET /browse_histories/ HTTP/1.1" 200 1060
INFO 2018-10-27 12:12:05,648 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2018-10-27 12:12:06,149 basehttp 124 "GET /user/ HTTP/1.1" 200 82
INFO 2018-10-27 12:12:06,165 basehttp 124 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
INFO 2018-10-27 12:12:06,279 basehttp 124 "GET /browse_histories/ HTTP/1.1" 200 1060
INFO 2018-10-27 12:12:07,779 basehttp 124 "OPTIONS /orders/?page=1&page_size=5 HTTP/1.1" 200 0
WARNING 2018-10-27 12:12:07,884 basehttp 124 "GET /orders/?page=1&page_size=5 HTTP/1.1" 405 45
INFO 2018-10-27 12:12:09,276 basehttp 124 "OPTIONS /addresses/ HTTP/1.1" 200 0
INFO 2018-10-27 12:12:09,368 basehttp 124 "GET /areas/ HTTP/1.1" 200 1204
INFO 2018-10-27 12:12:09,455 basehttp 124 "GET /addresses/ HTTP/1.1" 200 327
INFO 2018-10-27 12:12:12,872 basehttp 124 "GET /areas/ HTTP/1.1" 200 1204
INFO 2018-10-27 12:12:12,930 basehttp 124 "GET /addresses/ HTTP/1.1" 200 327
INFO 2018-10-27 14:53:40,968 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 200 195
INFO 2018-10-27 14:53:42,514 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 200 195
INFO 2018-10-27 14:54:02,433 basehttp 124 "GET /oauth/qq/user/?code=473B5933EDED5E5FF467705DADFB3F49 HTTP/1.1" 200 218
INFO 2018-10-27 14:54:19,380 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2018-10-27 14:54:19,505 basehttp 124 "GET /user/ HTTP/1.1" 200 88
INFO 2018-10-27 14:54:19,551 basehttp 124 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
INFO 2018-10-27 14:54:19,776 basehttp 124 "GET /browse_histories/ HTTP/1.1" 200 2
INFO 2018-10-27 14:54:29,104 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
INFO 2018-10-27 14:54:29,227 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 204
INFO 2018-10-27 14:54:35,182 basehttp 124 "GET /user/ HTTP/1.1" 200 82
INFO 2018-10-27 14:54:35,292 basehttp 124 "GET /browse_histories/ HTTP/1.1" 200 1060
INFO 2018-10-27 14:55:19,406 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
INFO 2018-10-27 14:55:19,576 basehttp 124 "GET /cart/ HTTP/1.1" 200 500
INFO 2018-10-27 14:55:32,168 basehttp 124 "GET /cart/ HTTP/1.1" 200 500
INFO 2018-10-27 14:55:34,790 basehttp 124 "OPTIONS /addresses/ HTTP/1.1" 200 0
INFO 2018-10-27 14:55:34,922 basehttp 124 "GET /areas/ HTTP/1.1" 200 1204
INFO 2018-10-27 14:55:35,006 basehttp 124 "GET /addresses/ HTTP/1.1" 200 327
INFO 2018-10-27 14:55:43,275 basehttp 124 "GET /user/ HTTP/1.1" 200 82
INFO 2018-10-27 14:55:43,366 basehttp 124 "GET /browse_histories/ HTTP/1.1" 200 1060
